### ISSUE TITLE
显示抢票失败

### ISSUE THREAD

**Issue by wittytang** [ClassmateLin/dm-ticket#10]
![image](https://github.com/ClassmateLin/dm-ticket/assets/48836821/368a1184-fa59-430f-8dcc-74aefd9c1c56)

**Comment by ClassmateLin** [comment]
token-server 启动成功没有， cookie复制的是不是完整的。

**Comment by zhuwei12** [comment]
+1

**Comment by wittytang** [comment]
网页端直接请求里 直接复制的cookie不知道  有什么问题

**Comment by lghcode** [comment]
我也碰到了同样的报错，token server启动成功，cookie复制了全部的
