### ISSUE TITLE
78楼你是SB吗，作者辛苦开源出来，是给你喷的吗？

### ISSUE THREAD

**Issue by lghcode** [ClassmateLin/dm-ticket#101]
我也是服了，大麦抢票本来就是和发送请求快慢没有多大关系，大部分还是看账号和运气的，希望作者不要被78楼影响到，我支持你

**Comment by Vonazzz** [comment]
确实 纯靠运气的玩意 能抢到就正好 抢不到就图一乐 也不知道他有啥好急的

**Comment by nullptr0807** [comment]
服了……

**Comment by xiaose-code** [comment]
你妈死了？嘴巴这么臭，有家教？书白读了？关你什么事了？

**Comment by lghcode** [comment]
> 你妈死了？嘴巴这么臭，有家教？书白读了？关你什么事了？

你才是没家教的东西，知道吗

**Comment by WaNuBigBeardTL** [comment]
确实第一次见素质这么差的程序员，能不能抢到，自己写过代码么？心里没数么？
