### ISSUE TITLE
请教大佬，群晖Docker该如何配置

### ISSUE THREAD

**Issue by Onloker** [ClassmateLin/dm-ticket#106]
![image](https://github.com/ClassmateLin/dm-ticket/assets/63253274/466de416-4c8e-45e1-a403-49c1aa965c57)
映射文件夹这样配置无效

![image](https://github.com/ClassmateLin/dm-ticket/assets/63253274/a0181365-4954-49a8-a130-5203324fca93)
这是配置完的

![image](https://github.com/ClassmateLin/dm-ticket/assets/63253274/fd93e396-ac9e-4bb4-ab5e-07bf0e444958)
这是运行日志

大佬，请问该如果改配置文件啊

**Comment by ClassmateLin** [comment]
装载路径是/src/config

Onloker ***@***.***> 于2023年5月31日周三 22:03写道：

**Comment by xssviggo** [comment]
装一个portainer，创建一个堆栈，直接把compose文件内容复制丢进去，改一下映射目录，取消两个镜像的端口的注释，让三个镜像都在同一个网段。启动！

**Comment by mbskter** [comment]
我是直接ssh进群晖直接命令行操作 方便~！
