### ISSUE TITLE
生成订单失败, invalid type: map, expected unit struct OrderInfoEndpoint

### ISSUE THREAD

**Issue by 13112442872** [ClassmateLin/dm-ticket#108]
生成订单失败, invalid type: map, expected unit struct OrderInfoEndpoint 一直是这个问题
![微信截图_20230601005046](https://github.com/ClassmateLin/dm-ticket/assets/24386690/f6a27a22-25f3-4b92-a7dc-5430d960868f)

**Comment by ClassmateLin** [comment]
重新拉镜像
