### ISSUE TITLE
您选购的商品信息已过期，请重新查询

### ISSUE THREAD

**Issue by 18170967136** [ClassmateLin/dm-ticket#110]
请问大家有碰到过这个问题吗？网站上面显示暂不可售，但是通过docker服务读回来的信息已经显示开抢了。
![image](https://github.com/ClassmateLin/dm-ticket/assets/49424306/9dea6476-d106-40a9-bb5f-aeced43cc49c)
![image](https://github.com/ClassmateLin/dm-ticket/assets/49424306/b0257257-0c59-4ea5-b7c4-9e3288b8294a)

**Comment by 18170967136** [comment]
望各位大佬解答。感谢！

**Comment by Lotus-Blue** [comment]
你是来搞笑的吗...都还没开售

**Comment by lghcode** [comment]
H5大麦，别总是看pc大麦

**Comment by 18170967136** [comment]
> 

我是看着docker上面显示已开售了，所以才问的

**Comment by 18170967136** [comment]
> H5大麦，别总是看pc大麦

好的，怎么进H5页面呀，能请教一下吗

**Comment by Lotus-Blue** [comment]
> > 
> 
> 我是看着docker上面显示已开售了，所以才问的

网页上面不是显示还没开售吗

**Comment by 18170967136** [comment]
> 

就是因为docker和网页显示的不一样，所以才疑惑呀

**Comment by Lotus-Blue** [comment]
> > 
> 
> 就是因为docker和网页显示的不一样，所以才疑惑呀

兄弟你可能没搞过工程，有时候开发的时间赶，把不成功的请求都设置为了一类提醒了，这个我估计也是，你不要纠结这个阿。。。

**Comment by 18170967136** [comment]
> 

好的，谢谢！

**Comment by Lotus-Blue** [comment]
> > 
> 
> 好的，谢谢！

你拿汪峰的来测试，没问题的话就行了，接下来就看运气了，

**Comment by 18170967136** [comment]
> > > 
> > 
> > 
> > 好的，谢谢！
> 
> 你拿汪峰的来测试，没问题的话就行了，接下来就看运气了，

好的，谢谢。emm，还有一个问题，就是我的cooke是不是会过期呀，是不是最好在开售前，更新一下cooke，最好提前多久进行更新呢？

**Comment by Lotus-Blue** [comment]
> > > > 
> > > 
> > > 
> > > 好的，谢谢！
> > 
> > 
> > 你拿汪峰的来测试，没问题的话就行了，接下来就看运气了，
> 
> 好的，谢谢。emm，还有一个问题，就是我的cooke是不是会过期呀，是不是最好在开售前，更新一下cooke，最好提前多久进行更新呢？

提前几分钟感觉比较安全，没人知道cookie啥时候会过期，而且你挂那么久也是白等，没用

**Comment by 18170967136** [comment]
好，谢谢大佬指点！

**Comment by LHEway** [comment]
> > > 
> > 
> > 
> > 好的，谢谢！
> 
> 你拿汪峰的来测试，没问题的话就行了，接下来就看运气了，

大佬 你们有遇到manifest for docker.io/classmatelin/alitoken-server:latest not found

**Comment by 18170967136** [comment]
> 

没有遇到过你说的问题，重新部署拉取镜像试试

**Comment by liusiry** [comment]
哪位兄弟放一下镜像啊，下载不了了，manifest for docker.io/classmatelin/dm-ticket:v0.1.3 not found，三个镜像都没了
