### ISSUE TITLE
请求帮助，“网络开小差了”

### ISSUE THREAD

**Issue by zhanghan3** [ClassmateLin/dm-ticket#113]
<img width="1037" alt="image" src="https://github.com/ClassmateLin/dm-ticket/assets/96095448/cf6de50d-39dc-41ce-b4f3-f20cca3a331c">

cookie是扫码登陆拿到的，不知道哪里还有问题

<img width="698" alt="image" src="https://github.com/ClassmateLin/dm-ticket/assets/96095448/0add018f-c3cc-4da5-a1dd-a4b160c6fea9">

**Comment by ClassmateLin** [comment]
扫码登录。cookie2缺少了某个字段。有些用户可以用。有些用不了。

**Comment by xiaohanihan** [comment]
> 扫码登录。cookie2缺少了某个字段。有些用户可以用。有些用不了。

我从浏览器复制的cokkie也不可以
