### ISSUE TITLE
求助，cookie怎么获取

### ISSUE THREAD

**Issue by Catnap1** [ClassmateLin/dm-ticket#114]
为什么我登陆界面f12没有cookie呀
![image](https://github.com/ClassmateLin/dm-ticket/assets/89449239/34890a97-e967-491f-bb8b-7dcdc68af88f)

**Comment by Catnap1** [comment]
顺便问一下，H5在哪！！

**Comment by lghcode** [comment]
你刷新页面请求一下，看请求头

**Comment by Jack8Li** [comment]
cookie变的太快了。。。用机器人感觉比手动抢还累
