### ISSUE TITLE
启动服务报错

### ISSUE THREAD

**Issue by RedCarl** [ClassmateLin/dm-ticket#115]
root@pgyidc:~/dm-ticket# docker exec -it dm-ticket dm-ticket
 ERROR dm_ticket::config > did not find expected key at line 4 column 7, while parsing a block mapping at line 3 column 5
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/bin/ticket.rs:24:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by zhuzhu1001** [comment]
一样，请问解决了吗

**Comment by youaremywind** [comment]
1. 执行：docker network ls 找到dm-ticket_dm_network对应的 network id
2. 执行：docker network rm <network_id>
3. 执行：docker-compose up -d

**Comment by Ly-GGboy** [comment]
同样的问题，删除重新拉也一样
