### ISSUE TITLE
一直都是抢票失败，session过期

### ISSUE THREAD

**Issue by wjzcp** [ClassmateLin/dm-ticket#12]
应该怎么解决

**Comment by ClassmateLin** [comment]
cookie需要复制全部

**Comment by wjzcp** [comment]
> 我是复制全都的，是不是不需要抢的不行，还有抢票的我在两分钟内复制了cookie，然后运行，还是出现了session过期

**Comment by wjzcp** [comment]
bug已解决，感恩感恩

**Comment by lghcode** [comment]
> 

兄弟，你成功了吗，为啥我一直报错， 生成订单失败, ["RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试!"]

**Comment by LHNB521** [comment]
兄弟，你成功了吗，为啥我一直报错， 生成订单失败, ["RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试!"]

**Comment by Xchen1995** [comment]
之前成功了 突然开始都在报错..

**Comment by lghcode** [comment]
> 之前成功了 突然开始都在报错..

现在你也报这个错吗

**Comment by JIN-strong** [comment]
> 

复制了全部cookie，依旧报错呢

**Comment by ClassmateLin** [comment]
> > 
> 
> 复制了全部cookie，依旧报错呢

![image](https://github.com/ClassmateLin/dm-ticket/assets/53087849/2f3d8a7a-627d-4e52-b81f-18f14b0e9ef8)
