### ISSUE TITLE
求助大佬！单个docker内如何实现多账号抢购？

### ISSUE THREAD

**Issue by Konohahaha** [ClassmateLin/dm-ticket#121]
我看config文件里写了两个帐号，是不是可以实现多账号同时抢票？
但是我把帐号2的注释符号删掉之后，会报错

**Comment by Twelvecat** [comment]
注意缩进，你把缩进对齐和第一个对齐就好了

**Comment by Konohahaha** [comment]
> 注意缩进，你把缩进对齐和第一个对齐就好了

哦哦这样确实就解决了报错的问题。

新的问题是：帐号1和账号2使用了不同两个号的cookie，可是内容却是是相同的(cookie不同)

/src/dm-ticket # exec dm-ticket dm-ticket
 INFO  dm_ticket::ticket > 正在获取演唱会信息...
 INFO  dm_ticket::ticket > 正在获取演唱会信息...
 INFO  dm_ticket::ticket > 正在获取场次/票档信息...
 INFO  dm_ticket::ticket > 正在获取场次/票档信息...

        账号备注: 账号2
        账号昵称: 麦子2XfyH
        门票名称: 【武汉】五月天2023「好好好想见到你」武汉演唱会
        场次名称: 2023-06-23 周五 19:00
        票档名称: 看台855元
        开抢时间: 06月02日 10:55

        开抢倒计时:18小时:22分钟:19.716秒
        账号备注: 账号1
        账号昵称: 麦子2XfyH
        门票名称: 【武汉】五月天2023「好好好想见到你」武汉演唱会
        场次名称: 2023-06-23 周五 19:00
        票档名称: 看台855元
        开抢时间: 06月02日 10:55

**Comment by Twelvecat** [comment]
重新检查cookie是不是真的不一样，还有你可以改一改时间和档次看看，顺便看看你的两个账户的昵称是不是一样的。目前我测试用两个账户是没问题的。
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年6月1日 16:56
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            Xu ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [ClassmateLin/dm-ticket] 求助大佬！单个docker内如何实现多账号抢购？ (Issue #121)
        
      
    
  


注意缩进，你把缩进对齐和第一个对齐就好了

哦哦这样确实就解决了报错的问题。
新的问题是：帐号1和账号2使用了不同两个号的cookie，可是内容却是是相同的(cookie不同)
/src/dm-ticket # exec dm-ticket dm-ticket
INFO  dm_ticket::ticket > 正在获取演唱会信息...
INFO  dm_ticket::ticket > 正在获取演唱会信息...
INFO  dm_ticket::ticket > 正在获取场次/票档信息...
INFO  dm_ticket::ticket > 正在获取场次/票档信息...
    账号备注: 账号2
    账号昵称: 麦子2XfyH
    门票名称: 【武汉】五月天2023「好好好想见到你」武汉演唱会
    场次名称: 2023-06-23 周五 19:00
    票档名称: 看台855元
    开抢时间: 06月02日 10:55

    开抢倒计时:18小时:22分钟:19.716秒
    账号备注: 账号1
    账号昵称: 麦子2XfyH
    门票名称: 【武汉】五月天2023「好好好想见到你」武汉演唱会
    场次名称: 2023-06-23 周五 19:00
    票档名称: 看台855元
    开抢时间: 06月02日 10:55

**Comment by gtyxs04** [comment]
# 需要抢购的场次序号.
        sessions: 1
        # 需要抢购的票档序号
        grade: 1

请教一下这两个字段是对应啥啊？

**Comment by Konohahaha** [comment]
> 重新检查cookie是不是真的不一样，还有你可以改一改时间和档次看看，顺便看看你的两个账户的昵称是不是一样的。目前我测试用两个账户是没问题的。


多账号抢票成了，我发现得用无痕模式登录，保证cookie不一样，不然太容易串了，谢谢你

**Comment by gtyxs04** [comment]
> > 重新检查cookie是不是真的不一样，还有你可以改一改时间和档次看看，顺便看看你的两个账户的昵称是不是一样的。目前我测试用两个账户是没问题的。
> 
> 多账号抢票成了，我发现得用无痕模式登录，保证cookie不一样，不然太容易串了，谢谢你

你好，可以请教一下 场次序号与票档序号 是看哪个字段呢？

**Comment by Konohahaha** [comment]
> > > 重新检查cookie是不是真的不一样，还有你可以改一改时间和档次看看，顺便看看你的两个账户的昵称是不是一样的。目前我测试用两个账户是没问题的。
> > 
> > 
> > 多账号抢票成了，我发现得用无痕模式登录，保证cookie不一样，不然太容易串了，谢谢你
> 
> 你好，可以请教一下 场次序号与票档序号 是看哪个字段呢？

你看一下readme里面有教你怎么数的

**Comment by gtyxs04** [comment]
弄好了谢谢你～

**Comment by wwlwwl2000** [comment]
这边大麦脚本可长期提供，有需要的来➕q2091248098，标明github
