### ISSUE TITLE
执行命令失败

### ISSUE THREAD

**Issue by shuoshadow** [ClassmateLin/dm-ticket#124]
![image](https://github.com/ClassmateLin/dm-ticket/assets/10016360/950f9b0d-d8ac-42e7-bdbe-c78e99989e1d)

**Comment by shuoshadow** [comment]
> 把token_server 重启下

谢谢可以了

**Comment by Leehom0512** [comment]
> 把token_server 重启下

重启了也还是这样我的

**Comment by HT944** [comment]
我重启，重新部署也都还是这样

**Comment by flowyears** [comment]
多重启两次试试，我一开始重启也还是报错，多试两次就好了
