### ISSUE TITLE
更新0.13后，windows docker运行脚本有问题

### ISSUE THREAD

**Issue by Basakerone** [ClassmateLin/dm-ticket#125]
releases下载到本地的0.1.1- 0.1.2都能正常。0.1.3运行脚本时候报错了，请问是不是我操作有问题。
![issues](https://github.com/ClassmateLin/dm-ticket/assets/17926247/dc65d5f1-a248-47a1-9e9c-31e05b29697a)

**Comment by Mrkongbairow** [comment]
这报错不是在写着呢么，这个容器都没运行起来
