### ISSUE TITLE
docker 启动抢票功能报错：格式问题

### ISSUE THREAD

**Issue by huchuansai** [ClassmateLin/dm-ticket#129]
截图：
<img width="1791" alt="image" src="https://github.com/ClassmateLin/dm-ticket/assets/50079978/a4ca136a-5193-4c32-928f-1b196f830847">

详细配置：
accounts:
    # .damai.cn中的cookie完整字符串
    - cookie: "_m_h5_tk=f4fe788920d4b2e42a6c9e9ef5cb6ec5_1685622452243; _m_h5_tk_enc=4ad83a83ea4be7666536f8bf5aa786cd; _samesite_flag_=true; cookie2=16dcaeb80fd4e953cbfb5b1cb25fc2f8; t=0d850de2fe63a82c5062c01d73b0d7b7; _tb_token_=eb4b65651e787; _hvn_login=18; munb=3747476398; csg=bfab3586; l=fBPmC4SgNwImgsdJBO5Znurza77OZIRfGfVzaNbMiIEGa6MltFidRNC_WY89SdtjgTfxZHKy58T6YdnwPS4LSAkDBeYBerBEMxv9-iQWnr1..; usercode=91088537; dm_nickname=%E9%BA%A6%E5%AD%90; havanaId=3747476398; isg=BODgSQkOkFtn4CxfZL390Yiiseiy6cSz4mHOelrzFfsJVYR_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      remark: "132100xx630"
      # 抢票轮训间隔, 单位毫秒
      interval: 30

      # 最早提前多少毫秒发包。 开抢剩余时间戳 = 开始售票的时间戳 - 当前时间戳。 当开抢剩余时间戳时间小于 submit_time时, 开始发送数据包。
      earliest_submit_time: 5

      # 请求时间 时间戳毫秒 用于捡漏 . 例如 50分是开票时间 但没有抢到,那么这里可以设置55分再抢一次,可能抢到二次放出的票
      # 1685415600100
      request_time: -1

      # 重试次数 
      retry_times: 2000

      # 重试间隔 单位毫秒
      retry_interval: 100

      ticket:
        # 需要抢购的门票ID, 门票详情页URL中的itemId.如:https://m.damai.cn/damai/detail/item.html?utm=&itemId=710947802955
        id: "721216860314"
        # 需要抢购的门票数量
        num: 2
        # 需要抢购的场次序号.
        sessions: 3
        # 需要抢购的票档序号
        grade: 2

**Comment by huchuansai** [comment]
排查了好几次了 并没有发现哪有问题 有成功抢到票上岸的同学吗

**Comment by ReddotCleaner** [comment]
这个cookie是你扫码登录之后获取到的吗？看起来格式和扫码获取到的不太一样

**Comment by aa542784252** [comment]
我也这个问题

**Comment by qsyQAQ** [comment]
你的重试次数太多了

**Comment by huchuansai** [comment]
失败
<img width="1244" alt="image" src="https://github.com/ClassmateLin/dm-ticket/assets/50079978/501b6990-831b-4055-8fc1-eec2afd86caf">

**Comment by Jeremy0309** [comment]
> 截图： <img alt="image" width="1791" src="https://user-images.githubusercontent.com/50079978/242569283-a4ca136a-5193-4c32-928f-1b196f830847.png">
> 
> 详细配置： accounts: # .damai.cn中的cookie完整字符串 - cookie: "_m_h5_tk=f4fe788920d4b2e42a6c9e9ef5cb6ec5_1685622452243; _m_h5_tk_enc=4ad83a83ea4be7666536f8bf5aa786cd; _samesite_flag_=true; cookie2=16dcaeb80fd4e953cbfb5b1cb25fc2f8; t=0d850de2fe63a82c5062c01d73b0d7b7; _tb_token_=eb4b65651e787; _hvn_login=18; munb=3747476398; csg=bfab3586; l=fBPmC4SgNwImgsdJBO5Znurza77OZIRfGfVzaNbMiIEGa6MltFidRNC_WY89SdtjgTfxZHKy58T6YdnwPS4LSAkDBeYBerBEMxv9-iQWnr1..; usercode=91088537; dm_nickname=%E9%BA%A6%E5%AD%90; havanaId=3747476398; isg=BODgSQkOkFtn4CxfZL390Yiiseiy6cSz4mHOelrzFfsJVYR_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" remark: "132100xx630" # 抢票轮训间隔, 单位毫秒 interval: 30
> 
> ```
>   # 最早提前多少毫秒发包。 开抢剩余时间戳 = 开始售票的时间戳 - 当前时间戳。 当开抢剩余时间戳时间小于 submit_time时, 开始发送数据包。
>   earliest_submit_time: 5
> 
>   # 请求时间 时间戳毫秒 用于捡漏 . 例如 50分是开票时间 但没有抢到,那么这里可以设置55分再抢一次,可能抢到二次放出的票
>   # 1685415600100
>   request_time: -1
> 
>   # 重试次数 
>   retry_times: 2000
> 
>   # 重试间隔 单位毫秒
>   retry_interval: 100
> 
>   ticket:
>     # 需要抢购的门票ID, 门票详情页URL中的itemId.如:https://m.damai.cn/damai/detail/item.html?utm=&itemId=710947802955
>     id: "721216860314"
>     # 需要抢购的门票数量
>     num: 2
>     # 需要抢购的场次序号.
>     sessions: 3
>     # 需要抢购的票档序号
>     grade: 2
> ```

方便提供一下yml文件么，我也是说格式问题，但是yml格式助手都能校验过
