### ISSUE TITLE
报错 thread main panicked at :./config/config.yaml'src/config.rs:37:59 有人遇到吗？

### ISSUE THREAD

**Issue by qqq520QQQ** [ClassmateLin/dm-ticket#131]
在运行docker exec -it dm-ticket dm-ticket出现问题
![uTools_1685619893553](https://github.com/ClassmateLin/dm-ticket/assets/44323252/9c4c58f7-d98d-448c-b0c8-b25da2843246)

**Comment by qsyQAQ** [comment]
我是把默认的.example文件改成了.yaml文件，再修改相关配置
