### ISSUE TITLE
提交订单失败, 原因:B-00203-100-037::您输入的联系人含特殊字符或长度不符

### ISSUE THREAD

**Issue by qsyQAQ** [ClassmateLin/dm-ticket#132]
![image](https://github.com/ClassmateLin/dm-ticket/assets/135232792/839cb4db-49fb-4fcb-8e06-05e6cd0023bb)
大伙有遇到这个问题的吗

**Comment by qsyQAQ** [comment]
解决了，因为是新号，在收货地址中新建了一个收件人就可以了

**Comment by wulongwang** [comment]
> 

启动不了呀，你是怎么启动的呢？
<img width="730" alt="image" src="https://github.com/ClassmateLin/dm-ticket/assets/3376097/24f4a109-94c2-44bf-9f1d-f8ad9aaf75f7">
