### ISSUE TITLE
Translate the `README.md` file to English language to make the code more open.

### ISSUE THREAD

**Issue by imranaai** [ClassmateLin/dm-ticket#136]
A good start would be to translate the `README.md` file into English to make the project reachable to the largest community on `Github`.

**Comment by jyC23333** [comment]
This is a private project for Chinese. 
Don't worry, you will never need this if you do not live in China.

**Comment by imranaai** [comment]
> This is a private project for Chinese. 
> Don't worry, you will never need this if you do not live in China.

Thanks for the information.
