### ISSUE TITLE
流量限制是怎么回事呀

### ISSUE THREAD

**Issue by wangwai1** [ClassmateLin/dm-ticket#138]
INFO  dm_ticket::ticket > 正在获取演唱会信息...
 ERROR dm_ticket::ticket > 获取门票信息失败, 结果:["FAIL_SYS_TRAFFIC_LIMIT::流量限制"]
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: 获取门票信息失败...', src/bin/ticket.rs:32:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by chenyuhua321** [comment]
+1 昨天还好好的

**Comment by chenyuhua321** [comment]
忽略，我是填错门票id了
