### ISSUE TITLE
票都被抢完了还在倒计时？

### ISSUE THREAD

**Issue by qsyQAQ** [ClassmateLin/dm-ticket#145]
![image](https://github.com/ClassmateLin/dm-ticket/assets/135232792/9f2aaa0e-60fb-4ce0-825c-a2284672eee1)
我开了两台服务器抢，配置上基本没区别，这种情况是啥意思

**Comment by xiaofsu** [comment]
<img width="686" alt="image" src="https://github.com/ClassmateLin/dm-ticket/assets/46067472/5c0c3880-f92c-4dff-a78f-409f8459369b">

**Comment by crywolfx** [comment]
我也是，😭，这俩原来冲突，我还以为能抢两次

**Comment by sdokio** [comment]
我也一样，理解错误导致错过抢票时间

**Comment by AnsonCong** [comment]
+1

**Comment by qsyQAQ** [comment]
> 我也是，😭，这俩原来冲突，我还以为能抢两次

我是两台服务器两个大麦账号两个票档，二者没有联系，而服务器1抢票失败，服务器2倒计时错乱。。。

**Comment by aclstack** [comment]
这个设置没太懂，如果是有优先购票的那种咋设置普通用户？

**Comment by ClassmateLin** [comment]
> 这个设置没太懂，如果是有优先购票的那种咋设置普通用户？

有优先购的APP会显示优先购时间, 如12:00(这个跟h5的时间开抢时间一致)开抢, 还会显示一个正式开抢的时间，如12:20分正式开抢。则将配置中的priority_purchase_time设置成20
