### ISSUE TITLE
感谢大佬带我看上五月天

### ISSUE THREAD

**Issue by svcvit** [ClassmateLin/dm-ticket#148]
感谢大佬带我看上五月天，感谢汪峰陪伴测试～～
![Xnip2023-06-02_11-43-16](https://github.com/ClassmateLin/dm-ticket/assets/3839507/da979660-0f3c-4027-b91e-dc798999fc2a)
![Xnip2023-06-02_11-43-27](https://github.com/ClassmateLin/dm-ticket/assets/3839507/7644cb45-a714-4bfb-941c-23b51e357592)

**Comment by sdokio** [comment]
我：老奸巨猾，居然提前测试，搞清了每个配置项
汪峰：我谢谢你

**Comment by qmkkxtxby** [comment]
电报群是多少，看不到了

**Comment by hsinyan7** [comment]
可以看看配置项吗

**Comment by sillyguodong** [comment]
> 电报群是多少，看不到了

+1

**Comment by svcvit** [comment]
> 可以看看配置项吗

全默认，就改了 cookie 和演出信息。

**Comment by svcvit** [comment]
> 电报群是多少，看不到了

https://t.me/+2EELgNTYiMYxMTFl

**Comment by EddyBuntz** [comment]
我今天也是抢五月天武汉站，没有早点发现这个项目，人麻了

**Comment by geekfaith** [comment]
这个不是只能抢网页上的吗，五月天这种它是要求手机抢，需要抢购的门票ID怎么获取到的呀

**Comment by Ly-GGboy** [comment]
> 这个不是只能抢网页上的吗，五月天这种它是要求手机抢，需要抢购的门票ID怎么获取到的呀

手机版也有网页啊，作者给的那个就是手机版的网页
