### ISSUE TITLE
各位大哥这个咋配置

### ISSUE THREAD

**Issue by lessuit** [ClassmateLin/dm-ticket#149]
The Compose file './docker-compose.yml' is invalid because:
networks.dm_network.ipam.config value Additional properties are not allowed ('gateway' was unexpected)

**Comment by mohui1999** [comment]
我也是遇到了这样的问题

**Comment by source-xu** [comment]
version: "3"

networks:
  dm_network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.88.0.0/24
        #gateway: 172.88.0.1
把网关注释掉

**Comment by lessuit** [comment]
1. 执行：docker network ls 找到dm-ticket_dm_network对应的 network id
2. 执行：docker network rm <network_id>
3. 执行：docker-compose up -d
4. 直接删掉网关那一行或者注释掉#gateway: 172.88.0.1

**Comment by mohui1999** [comment]
已解决，感谢！

**Comment by lessuit** [comment]
> version: "3"
> 
> networks: dm_network: driver: bridge ipam: driver: default config: - subnet: 172.88.0.0/24 #gateway: 172.88.0.1 把网关注释掉
