### ISSUE TITLE
请问联系人含特殊字符或长度不符如何解决

### ISSUE THREAD

**Issue by William-wAng618** [ClassmateLin/dm-ticket#15]
INFO  dm_ticket::dm > 成功生成订单...
 INFO  dm_ticket::dm > 提交订单失败, 原因:B-00203-100-037::您输入的联系人含特殊字符或长度不符，请修改后重新提交, 此次抢购花费时间:615.134547ms
 INFO  dm_ticket::dm > 成功生成订单...
 INFO  dm_ticket::dm > 提交订单失败, 原因:B-00203-100-037::您输入的联系人含特殊字符或长度不符，请修改后重新提交, 此次抢购花费时间:590.112606ms

**Comment by ClassmateLin** [comment]
请先填写观影人信息

**Comment by pawnjiang** [comment]
出现了相同问题，观演人信息是填写了的，但是一直报这个错

**Comment by ahuai** [comment]
![image](https://github.com/ClassmateLin/dm-ticket/assets/31682683/82c3e16d-2410-4210-a376-c915c591ebe9)
我也出现了这个问题  已经添加了购票人信息 估计是联系人的名字问题  还请博主看看

**Comment by yangzhiqiangq** [comment]
我在H5端 添加联系人之后也不行，还是这个错
