### ISSUE TITLE
启动镜像遇到错误

### ISSUE THREAD

**Issue by Zzealot1** [ClassmateLin/dm-ticket#151]
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: error sending request for url (http://token-server:8080/?key=bx_token): error trying to connect: dns error: failed to lookup address information: Name does not resolve

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
root@docker:~/Kyouka/qd/dm-ticket/docker-mysql/dm-ticket# docker exec -it dm-ticket dm-ticket
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: error sending request for url (http://token-server:8080/?key=bx_token): error trying to connect: dns error: failed to lookup address information: Name does not resolve

怎么办啊

**Comment by Lotus-Blue** [comment]
cao，我最新版本也是这样

**Comment by Lotus-Blue** [comment]
cao，我最新版本也是这样

**Comment by RoseEnd** [comment]
me too

**Comment by RoseEnd** [comment]
"./zzdns:/usr/local/zzdns/config" 改成 "./zzdns:/usr/local/config" 就可以了

**Comment by zhenzhenhan** [comment]
> 
好像不行唉，我改了还是报错

**Comment by Jeremy0309** [comment]
> "./zzdns:/usr/local/zzdns/config" 改成 "./zzdns:/usr/local/config" 就可以了

这是修改的哪个文件呢
