### ISSUE TITLE
镜像拉取失败

### ISSUE THREAD

**Issue by Leehom0512** [ClassmateLin/dm-ticket#153]
`[root@dm dm-ticket]# docker pull classmatelin/alitoken-server:latest
Trying to pull repository docker.io/classmatelin/alitoken-server ... 
manifest for docker.io/classmatelin/alitoken-server:latest not found
`
求解决

**Comment by source-xu** [comment]
我用腾讯云也拉取失败但是amazon云可以我用amazon云把要的镜像pull到本地打成tar包复制到服务器上load进去解决的
