### ISSUE TITLE
各位大哥docker exec -it dm-ticket dm-ticket启动报错咋解决呀

### ISSUE THREAD

**Issue by YaToWei-dd** [ClassmateLin/dm-ticket#154]
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: error sending request for url (https://mtop.damai.cn/h5/mtop.damai.wireless.search.broadcast.list/1.0/?): error trying to connect: dns error: failed to lookup address information: Try again

Caused by:
    0: error trying to connect: dns error: failed to lookup address information: Try again
    1: dns error: failed to lookup address information: Try again
    2: failed to lookup address information: Try again', src/bin/ticket.rs:31:66

**Comment by UDDDDD** [comment]
跟你一样的，不知道什么情况。
