### ISSUE TITLE
真实使用情况结果收集

### ISSUE THREAD

**Issue by source-xu** [ClassmateLin/dm-ticket#155]
想看看大家用这个脚本的实际情况
抢到/没抢到 成功率咋样

**Comment by Andy-Leong** [comment]
没抢到
![21521685674817_ pic](https://github.com/ClassmateLin/dm-ticket/assets/15701788/91dc29ed-bd85-4d7c-ae09-217e65e3db20)

**Comment by huchuansai** [comment]
<img width="1505" alt="image" src="https://github.com/ClassmateLin/dm-ticket/assets/50079978/a6eb8999-bf95-42d1-ba3a-be441ca655e6">

**Comment by m0cun** [comment]
5G 热点环境，ping 延迟 10～30ms左右。
左边docker 部署，修改了【earliest_submit_time: 6；retry_times: 5】其他为默认，未抢到。
右边源码抢票，修改了【earliest_submit_time: 10；retry_times: 5】其他为默认，第二次抢到。
<img width="1434" alt="image" src="https://github.com/ClassmateLin/dm-ticket/assets/62125244/59126ca0-6465-40fe-8aeb-720b15cfced1">

**Comment by Mrkongbairow** [comment]
![image](https://github.com/ClassmateLin/dm-ticket/assets/46020591/5e8bee4a-621a-4462-9092-aa74dd0411b2)

**Comment by source-xu** [comment]
> 5G 热点环境，ping 延迟 10～30ms左右。 左边docker 部署，修改了【earliest_submit_time: 6；retry_times: 5】其他为默认，未抢到。 右边源码抢票，修改了【earliest_submit_time: 10；retry_times: 5】其他为默认，第二次抢到。 <img alt="image" width="1434" src="https://user-images.githubusercontent.com/62125244/242804819-59126ca0-6465-40fe-8aeb-720b15cfced1.png">

老哥你这两个环境开抢前是同时运行的吗

**Comment by m0cun** [comment]
> > 5G 热点环境，ping 延迟 10～30ms左右。 左边docker 部署，修改了【earliest_submit_time: 6；retry_times: 5】其他为默认，未抢到。 右边源码抢票，修改了【earliest_submit_time: 10；retry_times: 5】其他为默认，第二次抢到。 <img alt="image" width="1434" src="https://user-images.githubusercontent.com/62125244/242804819-59126ca0-6465-40fe-8aeb-720b15cfced1.png">
> 
> 老哥你这两个环境开抢前是同时运行的吗

是的，都部署在自己的电脑上，同时开抢。

**Comment by lghcode** [comment]
![image](https://github.com/ClassmateLin/dm-ticket/assets/36762378/80637c3c-4cee-4c43-ab99-307974c916a6)
张韶涵的抢到了

**Comment by sljeff** [comment]
各位成功的用户，是使用扫码登陆的 cookie 还是移动版网页的 cookie 呢

**Comment by super72** [comment]
> 5G 热点环境，ping 延迟 10～30ms左右。 左边docker 部署，修改了【earliest_submit_time: 6；retry_times: 5】其他为默认，未抢到。 右边源码抢票，修改了【earliest_submit_time: 10；retry_times: 5】其他为默认，第二次抢到。 <img alt="image" width="1434" src="https://user-images.githubusercontent.com/62125244/242804819-59126ca0-6465-40fe-8aeb-720b15cfced1.png">
请问你两边的命令行都是提前一秒开始运行的吗？是手动还是有其他方法？

**Comment by m0cun** [comment]
> > 5G 热点环境，ping 延迟 10～30ms左右。 左边docker 部署，修改了【earliest_submit_time: 6；retry_times: 5】其他为默认，未抢到。 右边源码抢票，修改了【earliest_submit_time: 10；retry_times: 5】其他为默认，第二次抢到。 <img alt="image" width="1434" src="https://user-images.githubusercontent.com/62125244/242804819-59126ca0-6465-40fe-8aeb-720b15cfced1.png">
> > 请问你两边的命令行都是提前一秒开始运行的吗？是手动还是有其他方法？

你把这个程序运行起来就知道了，对于未开售的门票，会自动开启倒计时功能，左右两边只需要提前分别启动就行，剩下的交给倒计时，时间一到会自动开抢。

**Comment by CookieJaySJ** [comment]
> 

老哥请问一下，对于未开售的门票，开启自动倒计时后，我可以把命令行窗口关闭么？  还是得一直保持着打开状态才能在开票时间点购票？

**Comment by CookieJaySJ** [comment]
> > > 5G 热点环境，ping 延迟 10～30ms左右。 左边docker 部署，修改了【earliest_submit_time: 6；retry_times: 5】其他为默认，未抢到。 右边源码抢票，修改了【earliest_submit_time: 10；retry_times: 5】其他为默认，第二次抢到。 <img alt="image" width="1434" src="https://user-images.githubusercontent.com/62125244/242804819-59126ca0-6465-40fe-8aeb-720b15cfced1.png">
> > > 请问你两边的命令行都是提前一秒开始运行的吗？是手动还是有其他方法？
> 
> 你把这个程序运行起来就知道了，对于未开售的门票，会自动开启倒计时功能，左右两边只需要提前分别启动就行，剩下的交给倒计时，时间一到会自动开抢。
老哥请问一下，对于未开售的门票，开启自动倒计时后，我可以把命令行窗口关闭么？ 还是得一直保持着打开状态才能在开票时间点购票？
