### ISSUE TITLE
张韶涵的成功了

### ISSUE THREAD

**Issue by lghcode** [ClassmateLin/dm-ticket#156]
![image](https://github.com/ClassmateLin/dm-ticket/assets/36762378/acf0e9da-a780-4632-a30e-cb7fd4849e6b)
估计是张韶涵的没有很多人抢

**Comment by XiangtingLee** [comment]
580不用抢，现在还有

**Comment by lghcode** [comment]
> 580不用抢，现在还有

哈哈
