### ISSUE TITLE
抢到过的兄弟们，来分享一下使用经验吧

### ISSUE THREAD

**Issue by lghcode** [ClassmateLin/dm-ticket#157]
![a7546d180f9f8b1fb98cf23269e7ae6](https://github.com/ClassmateLin/dm-ticket/assets/36762378/8f15e547-19a8-4e67-96db-885768d884bf)

**Comment by endLife888** [comment]
大佬满了

**Comment by ZHP-LJH** [comment]
> 

有大佬邀请一下？

**Comment by flykingkkkk** [comment]
满了呀
