### ISSUE TITLE
现在汪峰的也买不成功了，是ip被黑了吗

### ISSUE THREAD

**Issue by lessuit** [ClassmateLin/dm-ticket#159]
![image](https://github.com/ClassmateLin/dm-ticket/assets/52142616/bdfeed7e-427e-48ec-b5fa-380336356d83)
最开始测试是可以买的，现在又不行了

**Comment by huangxy7** [comment]
啥也不贴，很难评论

**Comment by lessuit** [comment]
大麦网点击头像退出登录，再重新登录
