### ISSUE TITLE
被挤爆了！

### ISSUE THREAD

**Issue by qianbenhyu** [ClassmateLin/dm-ticket#160]
![image](https://github.com/ClassmateLin/dm-ticket/assets/32768810/94223cc0-c4e6-438f-817b-3522dbcb6144)
这是啥情况

**Comment by lghcode** [comment]
重新登录

**Comment by qianbenhyu** [comment]
还是不行...不能挂服务器上吗

**Comment by jyC23333** [comment]
好像是云服务器不行，登录公司VPN也不行，手机热点是可以的
