### ISSUE TITLE
这是什么情况呀 兄弟们cookie也重新设置了

### ISSUE THREAD

**Issue by YaToWei-dd** [ClassmateLin/dm-ticket#161]
![image](https://github.com/ClassmateLin/dm-ticket/assets/135002856/3e7d4773-8e92-4f95-bf18-7b2a6d23d101)

**Comment by MrZhaoC** [comment]
看一下是新登录后的cookie吗

**Comment by NicolasCxy** [comment]
我也一样，重新登录，新的cookie也是提示这个，求大佬帮忙啊
