### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by Jeremy0309** [ClassmateLin/dm-ticket#162]
![image](https://github.com/ClassmateLin/dm-ticket/assets/71264979/96a703e7-a626-473c-8bea-9a9132ecf7c8)

docker exec -it dm-ticket dm-ticket 启动后报错，哪个接口存在配置问题呀

**Comment by Moshimol** [comment]
我也是这个问题 小鲸鱼已经启动了呢 mac上的环境

**Comment by Jeremy0309** [comment]
docker ps
docker restart classmatelin/alitoken-server:v0.1.1
docker restart  token-server
或者
docker-compose down
docker-compose pull
docker-compose up -d
docker exec -it dm-ticket d
