### ISSUE TITLE
按两种方法复制cookie都提示["B-00203-200-100::网络开小差了，再试一次吧~"]

### ISSUE THREAD

**Issue by 18770171448** [ClassmateLin/dm-ticket#163]
<img width="1199" alt="1685693547567" src="https://github.com/ClassmateLin/dm-ticket/assets/50327084/c303800b-d1d7-4054-b262-58ea24829dbf">
<img width="671" alt="1685693600680" src="https://github.com/ClassmateLin/dm-ticket/assets/50327084/03c9fa02-677a-49cc-92d4-8e3cdb2c35c0">

**Comment by 18770171448** [comment]
<img width="1180" alt="1685693770677" src="https://github.com/ClassmateLin/dm-ticket/assets/50327084/32479853-f66b-456a-9761-c856a8251203">
这是配置信息

**Comment by 18770171448** [comment]
> 

我发现，是有些需要选座购买的，就有这个问题，换一个不需要选座的演出试试

**Comment by ClassmateLin** [comment]
不支持选座
