### ISSUE TITLE
【常见错误&提供援助】不理解什么是cookie &  cookie问题 & cookie过期 & 

### ISSUE THREAD

**Issue by huchuansai** [ClassmateLin/dm-ticket#168]

**Comment by huchuansai** [comment]
cookie一定要取对！！！！！！
<img width="1787" alt="image" src="https://github.com/ClassmateLin/dm-ticket/assets/50079978/29800050-59ea-4472-ae10-4449241bbb36">
<img width="1791" alt="image" src="https://github.com/ClassmateLin/dm-ticket/assets/50079978/5df28861-28dd-45d8-b62f-68778413c5ce">

**Comment by kiki53569** [comment]
<img width="1433" alt="截屏2023-06-04 11 29 10" src="https://github.com/ClassmateLin/dm-ticket/assets/135215446/7b58366a-a0e9-4784-9265-641d29066d48">
我这个对吗？
