### ISSUE TITLE
docker-compose失败

### ISSUE THREAD

**Issue by CaiZhy1997** [ClassmateLin/dm-ticket#17]
一直找不到image，版本号v0.1.0、v0.1.1都试过了。也加了镜像加速好像还是不行。是什么原因

**Comment by ClassmateLin** [comment]
[解决方案](https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&rsv_idx=1&tn=baidu&wd=docker%E6%97%A0%E6%B3%95%E6%8B%89%E5%8F%96%E9%95%9C%E5%83%8F&fenlei=256&rsv_pq=0x95f37840000e9a00&rsv_t=cf4fjLvZZ28CkxTUoYSd8E0vTk%2BT%2BZBlArwxwm64yiNdsGN8IGAhrlF7VXWa&rqlang=en&rsv_dl=tb&rsv_sug3=32&rsv_enter=1&rsv_sug1=20&rsv_sug7=100&rsv_sug2=0&rsv_btype=i&inputT=7584&rsv_sug4=7584)

**Comment by CaiZhy1997** [comment]
这个已经试过了
