### ISSUE TITLE
如何启动多个容器实现多账号一起抢票

### ISSUE THREAD

**Issue by geekfaith** [ClassmateLin/dm-ticket#170]
～

**Comment by ClassmateLin** [comment]
复制一下配置改容器名

**Comment by huchuansai** [comment]
主要是复制哪个容器？

**Comment by huchuansai** [comment]
![image](https://github.com/ClassmateLin/dm-ticket/assets/50079978/e26cf790-f751-480b-a06c-ba64f18d5dc0)
dm-ticket?

**Comment by echobigdata** [comment]
启动多个容器在docker-compose.yml里面配置吗
