### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: error sending request for url (http://172.88.0.2:8080/?key=bx_token): operation timed out

### ISSUE THREAD

**Issue by WyntersN** [ClassmateLin/dm-ticket#173]
CentOS Stream 8 x86_64
Linux 和win 都是这样报错，跑不起来
![image](https://github.com/ClassmateLin/dm-ticket/assets/27792650/4b11ad21-7954-4bd8-93f8-70a6ac22518a)

**Comment by WyntersN** [comment]
curl http://172.88.0.2:8080/?key=bx_token
一直不动

**Comment by Hbisedm** [comment]
我也遇到了这个问题

**Comment by Arch1eLiu** [comment]
我也遇到了这个问题

**Comment by java666888** [comment]
这个是怎么回事 我发现docker容器并没有映射端口

**Comment by java666888** [comment]
> 我现在改成用rust去跑，就可以了

clone这个项目 搭建rust环境才行吗

**Comment by Hbisedm** [comment]
> > 我现在改成用rust去跑，就可以了
> 
> 
> 
> clone这个项目 搭建rust环境才行吗 

是

**Comment by WyntersN** [comment]
> 这个是怎么回事 我发现docker容器并没有映射端口

我试过映射了也没用

**Comment by kts-kris** [comment]
重启 docker，不是重启镜像
