### ISSUE TITLE
使用1.0.4的release报错网关冲突解决办法

### ISSUE THREAD

**Issue by zhenhual** [ClassmateLin/dm-ticket#174]
执行docker-compose up -d报错：
`ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.dm_network.ipam.config value Additional properties are not allowed ('gateway' was unexpected)`
解决办法：将配置文件中的version：2
或者将gateway注释

**Comment by wht11394** [comment]
我是Cannot start service token-server: Address already in use

**Comment by zhenhual** [comment]
> 我是Cannot start service token-server: Address already in use

查看一下当前的ip 地址，ipconfig或者ip addr，然后看是不是和配置文件冲突了
