### ISSUE TITLE
1.0.4无法运行，run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### ISSUE THREAD

**Issue by worshipone** [ClassmateLin/dm-ticket#176]
<img width="503" alt="1685717281417" src="https://github.com/ClassmateLin/dm-ticket/assets/59354339/c36f1949-80c5-447e-a8e6-b0cf77665297">

**Comment by ClassmateLin** [comment]
配置格式填错了

**Comment by ZHP-LJH** [comment]
> 配置格式填错了
![微信图片_20230605105105](https://github.com/ClassmateLin/dm-ticket/assets/56819573/bdb89d98-9ab2-49be-9e08-6424fd417c74)
博主，这样写为啥还出现格式错误啊？
