### ISSUE TITLE
楼主咋整：["B-00203-200-100::网络开小差了，再试一次吧~"]

### ISSUE THREAD

**Issue by zhangjushun** [ClassmateLin/dm-ticket#18]
生成订单失败, ["B-00203-200-100::网络开小差了，再试一次吧~"]

**Comment by ClassmateLin** [comment]
cookie是否复制完整?

**Comment by LHNB521** [comment]
![image](https://github.com/ClassmateLin/dm-ticket/assets/45733827/c7ad3aa9-7220-4384-8fe8-86d9cdce0a19)

**Comment by LHNB521** [comment]
手机上可以直接购买的，抢票不可以买呀？不用选座的

**Comment by gryffindor-rr** [comment]
> cookie是否复制完整?

cookie复制完整，也重新登录过更新了cookie，但还是同样的错
 INFO  dm_ticket::dm > 生成订单失败, ["B-00203-200-100::网络开小差了，再试一次吧~"]
 INFO  dm_ticket::dm > 生成订单失败, ["B-00203-200-100::网络开小差了，再试一次吧~"]

**Comment by deplives** [comment]
同样的问题，是了好几个人的账号，试了好几场演唱会，都是这个问题

**Comment by StarSink9** [comment]
我也有这个问题

**Comment by ClassmateLin** [comment]
麻烦email发我个cookie试试

**Comment by firstfang** [comment]
> 

cna=3uj1HLC0VV4CARsRUVEz+eM/; t=e2e0bb550c9639330aa8ef943a896695; xlly_s=1; _m_h5_tk=9d653a1af8914c8d59fb0263bdcc29ff_1685377965143; _m_h5_tk_enc=b64b2c05383307a620a5ae12c3fd1540; _samesite_flag_=true; cookie2=1874aa3c336a2b23a12abf4aa55f91bd; _tb_token_=f51fd3ea30794; _hvn_login=18; munb=3840206074; csg=2c1c4853; l=fBr2rH7qN1SVfCkZBOfwFurza77tIIRdguPzaNbMi9fPOy1H5ubAW1aJZDTMCnGREsL2x3RlOucBB5YLJyUIgxv9-e98k9lxnddCDa90l; tfstk=ciFdB2TFwGj3FkIo_XBMz3pitV_camLt2TiwwWnHcYWvfHdkasxgiSIz8UgtWxbO.; usercode=95306175; dm_nickname=%E9%9B%84; havanaId=3840206074; isg=BKOjksn0w_7WNo_KhnMogsImMudNmDfay2Yv5NUA-YJ1FM82XWxXIb0FCsIatI_S

**Comment by firstfang** [comment]
有可能是场次问题，session和grade不能乱填，一定要在值范围内

**Comment by zycboss** [comment]
我们搞懂这个cookies，为什么我按照作者截图里面那个地方复制过来，和原本配置文件里的格式不一样? 没有cna啥的

**Comment by Smartisa** [comment]
我也出现了这个问题
