### ISSUE TITLE
五月天没办法正常抢票

### ISSUE THREAD

**Issue by Zzealot1** [ClassmateLin/dm-ticket#180]
杭州场
 生成订单失败, ["B-00203-200-034::您选购的商品信息已过期，请重新查询"]

沈阳场
获取演唱会信息失败, missing field `item` at line 1 column 43
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: missing field `item` at line 1 column 43', src/bin/ticket.rs:56:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

这是跑起来了还是没跑起来啊，晕掉了

**Comment by ClassmateLin** [comment]
选个有票的测试

**Comment by sti1l-0** [comment]
> Owner

选了个汪峰有票的测试 id="720545258599"，手机上能走到支付这一步，但是用docker跑起来提示
`
生成订单失败, ["FAIL_SYS_USER_VALIDATE", "RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试"]
`
