### ISSUE TITLE
Error response from daemon: manifest for classmatelin/dm-ticket:v0.1.5 not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by WyntersN** [ClassmateLin/dm-ticket#181]
classmatelin/dm-ticket:v0.1.5 是不是还没发布
 
 Error response from daemon: manifest for classmatelin/dm-ticket:v0.1.5 not found: manifest unknown: manifest unknown

**Comment by kts-kris** [comment]
hub 上没有这个镜像，要么用 0.1.4，要么去掉版本号
修改 docker-compose.yml  里 image: classmatelin/dm-ticket:v0.1.5  改为 image: classmatelin/dm-ticket

**Comment by WyntersN** [comment]
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: error sending request for url (http://172.88.0.2:8080/?key=bx_token): operation timed out

Caused by:
    operation timed out', src/bin/ticket.rs:52:66
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


还是和0.1.4版本 报错一样

**Comment by kts-kris** [comment]
这是另外一个错误了，我现在也是这个错误，tokenserver 超时

**Comment by kts-kris** [comment]
不是重启镜像，而是重启 docker 本身，我这成功了

**Comment by WyntersN** [comment]
重启 docker 再运行就能成功吗

**Comment by kts-kris** [comment]
/src/config/config.yaml
