### ISSUE TITLE
token server 超时的解决方案之一

### ISSUE THREAD

**Issue by kts-kris** [ClassmateLin/dm-ticket#187]
重启 docker，而不是重启 token server的镜像！
如果你有 docker desktop  直接重启
如果你用命令行  docker restart

**Comment by youaremywind** [comment]
没用

**Comment by kts-kris** [comment]
> 

看看你的防火墙，关掉试试。我重启 docker 而不是重启镜像后就好了，另外有一位也好了。

**Comment by youaremywind** [comment]
我没开防火墙

**Comment by java666888** [comment]
就是重启这个token-server的镜像就可以了
