### ISSUE TITLE
docker exec -it dm-ticket dm-ticket 运行错误

### ISSUE THREAD

**Issue by TonyD0g** [ClassmateLin/dm-ticket#188]
报错信息：
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: error sending request for url (http://172.88.0.2:8080/?key=bx_token): operation timed out

Caused by:
    operation timed out', src/bin/ticket.rs:52:66
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
-------------------------------------------------------------------------------------
我查看docker desktop发现 zzdns,token-server,dm-ticket都在运行，但还是报错

**Comment by tongbao96** [comment]
应该是你改了里面的参数，比如票档之类的

**Comment by TonyD0g** [comment]
config.yaml信息如下：
我猜测是我的cookie错了吗？我使用的是谷歌浏览器，用的是?jsv=2.6.1&appKey=xxxxx&t=xxxxx&sign=xxxxx&api=mtop.damai.mxm.user.accesstoken.getbytbs&v=1.0&type=jsonp&dataType=jsonp&callback=mtopjsonp1&data=%7B%7D这个url的cookie
-----------------------------------------
accounts:
    # .damai.cn中的cookie完整字符串
    - cookie: ""
      remark: "我的电话" 

      # 轮询判断当前时间是否大于等于可以请求数据的时间, 单位ms
      interval: 30

      # 自定义开抢时间戳, 单位:毫秒。 默认: -1, 自动获取开抢时间。
      request_time: -1

      # 最早提前多少毫秒发包。 开抢剩余时间戳 = 开始售票的时间戳 - 当前时间戳。 当开抢剩余时间戳时间小于submit_time时, 开始发送数据包。
      earliest_submit_time: 5

      # 生成订单成功后, 等待多久再提交订单,  单位毫秒
      wait_for_submit: 10

      # 抢票重试次数
      retry_times: 10

      # 重试间隔 单位毫秒
      retry_interval: 100

      ticket:
        # 需要抢购的门票ID, 门票详情页URL中的itemId.如:https://m.damai.cn/damai/detail/item.html?utm=&itemId=710947802955

        id: "721815323393"

        # 需要抢购的门票数量
        num: 1

        # 需要抢购的场次序号.
        sessions: 1
        
        # 需要抢购的票档序号
        grade: 2

        # 优先购的时长是多少分钟(app优先购开始时间等于h5的开抢时间, 实际上没有优先购资格的需要等10-20分钟不等)。默认: 0, 没有优先购
        # 如果有优先购, app会显示优先购时间和正式购买时间。
        # 例如优先购时间是12:00(这个时间与h5的开抢时间一致, 程序自动获取。如果设置了request_time, 则以request_time时间为准), 正式开售是12点10分。那么这个宽限期就配置: 10
        # 优先购结束后，会进入等待正式购流程。
        priority_purchase_time: 0


        # 配置实名人信息, 类型:数组。默认为空, 自动选前N(购票数量)位实名人。如购买2张票, 需要选择第一位和第三位实名人，则填入[1,3]。
        real_names: [1]

        # 捡漏配置
        pick_up_leaks:
          # 比如开抢时间12:00, 12:00之前启动程序的会自动进入捡漏模式。
          # 如果在12:00之后才启动程序的, 是否进入捡漏模式，取决于这个配置。单位: 分钟。
          # 默认5分钟, 即12:00 ~ 12:05启动程序的, 如果遇到商品已售空，则进入捡漏模式扫描库存。
          # 对于几个小时前就已经售空的票开捡漏模式是没有意义的。所以这个值不需要设置太大。设大了也没用。
          grace_period_minutes: 5

          # 捡漏票数设置, 默认0, 与上面抢票配置保持一致。
          num: 0

          # 轮询间隔, 单位毫秒
          interval: 2000

          # 轮询次数
          times: 100

          # 票档序号配置, 数组格式。默认空=有票就买, 只购买对应票档, 则填入序号。购买第一档和第三档则配置[1,3], 优先购买低票档。
          grades: []

**Comment by tongbao96** [comment]
real_names: [1]这个设成空列表试一下

**Comment by TonyD0g** [comment]
依旧不行，不知道哪里有错误

**Comment by TonyD0g** [comment]
![图片](https://github.com/ClassmateLin/dm-ticket/assets/85001557/3cedb7e4-e6ce-4754-8796-de86b198b9e6)

**Comment by tongbao96** [comment]
#173

**Comment by Xchen1995** [comment]
是不是重启docker就好了

**Comment by kts-kris** [comment]
#187

**Comment by TonyD0g** [comment]
重启docker后token-server就无法开启了，只能docker-compose down，然后再docker-compose up -d才能全部开启起来

**Comment by tongbao96** [comment]
我没遇到这个问题，但是刚刚抢张艺兴还是没抢到

**Comment by tongbao96** [comment]
![~ HUKBXK5H46GT1F((9DD 8](https://github.com/ClassmateLin/dm-ticket/assets/50855300/34296cd4-000a-47ac-ad6c-7e9daa3cc06c)

**Comment by TonyD0g** [comment]
> 

张艺兴我是用手机抢的，抢到了但是我一直付不了款（太卡），过十分钟订单没了。。。。

**Comment by tongbao96** [comment]
哈哈 付不了款等于没抢到。。。

**Comment by TonyD0g** [comment]
使用https://github.com/ClassmateLin/dm-ticket/issues/187解决成功，点击restart选项

![图片](https://github.com/ClassmateLin/dm-ticket/assets/85001557/e8082ea2-96ca-4260-89ae-91a1c7767180)

**Comment by tc358** [comment]
>重启了也是一样。。
![image](https://github.com/ClassmateLin/dm-ticket/assets/35983534/dfcbbbf2-90c2-4ec3-8d6d-fc4e6db30019)

**Comment by TonyD0g** [comment]
1.重启docker(docker restart)后使用docker-compose down，然后再docker-compose up -d
2.如果还不行，反复操作
3.依旧不行，就重启。然后重复上述操作

**Comment by tc358** [comment]
后面可以了，把 token-server那个 docker stop， 重新start下
