### ISSUE TITLE
生成订单失败, ["RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试!"]

### ISSUE THREAD

**Issue by lghcode** [ClassmateLin/dm-ticket#19]
![image](https://github.com/ClassmateLin/dm-ticket/assets/36762378/141ad0fe-8217-40d0-bbc0-d6dfa31609a5)
试了好几次，都是失败,cookie是完整的，另外token-server启动是成功的
![image](https://github.com/ClassmateLin/dm-ticket/assets/36762378/20655027-a51c-45cd-9221-b0945ecad22c)

**Comment by LHNB521** [comment]
我也是这样的

**Comment by ClassmateLin** [comment]
ip是否是家用ip

**Comment by Xchen1995** [comment]
公司IP会影响这个么

**Comment by lghcode** [comment]
> ip是否是家用ip

我这服务器是阿里云的，影响吗

**Comment by LHNB521** [comment]
本机可用

**Comment by Xchen1995** [comment]
> 本机可用

你好啦？

**Comment by LHNB521** [comment]
![image](https://github.com/ClassmateLin/dm-ticket/assets/45733827/9ba59754-7667-4ae6-bf1b-7869e0e2ddc7)

**Comment by LHNB521** [comment]
是的，测试的

**Comment by georgegao245** [comment]
有现票的能成功，但是倒计时抢票的没成功过，而且只循环抢票一次。

**Comment by Xchen1995** [comment]
> 是的，测试的

是换了wifi吗

**Comment by Xchen1995** [comment]
感觉是ip给大麦抓出来了 恶意请求

**Comment by ClassmateLin** [comment]
> > ip是否是家用ip
> 
> 我这服务器是阿里云的，影响吗

影响很大

**Comment by lghcode** [comment]
在电脑本机装了个docker，用的公司网络，可以了
