### ISSUE TITLE
有些演唱会能抢，有些不能抢？

### ISSUE THREAD

**Issue by TonyD0g** [ClassmateLin/dm-ticket#190]
黄绮珊的能抢，张泽和肖俊的不能抢
前面有名，后面的名气小。
难道是热度高的有保护机制？

**Comment by TonyD0g** [comment]
黄绮珊的会出现：“B-00203-200-100::网络开小差了，再试一次吧” 的错误
张泽，肖俊的不会出现这个错误

**Comment by ClassmateLin** [comment]
不支持选座
