### ISSUE TITLE
配置config.yaml场次错误

### ISSUE THREAD

**Issue by gdrpzym** [ClassmateLin/dm-ticket#192]
我填写的深圳杨长青的itemId=720472767866，为啥启动后总是显示抢购张艺兴的呢，无论我的config修改的是哪个ID,大佬们帮忙指导一下

<img width="1472" alt="Snipaste_2023-06-03_21-27-40" src="https://github.com/ClassmateLin/dm-ticket/assets/30324436/60b204d2-dd3c-473f-894d-8c5ae6adc01d">

**Comment by GitHubWebb** [comment]
看下你docker运行的容器和你配置config的是不是同一个
