### ISSUE TITLE
前三次能成功生成订单，但后面就报错哎哟喂,被挤爆啦,请稍后重试

### ISSUE THREAD

**Issue by orz789** [ClassmateLin/dm-ticket#193]
INFO  dm_ticket::ticket > 正在获取演唱会信息...
 INFO  dm_ticket::ticket > 正在获取场次/票档信息...

        账号备注: 账号1
        账号昵称: ADNDN
        门票名称: 【深圳】2023 张艺兴 「大航海2.5·无远弗届」巡回演唱会-深圳站
        场次名称: 2023-08-05 周六 19:30
        票档名称: 看台 1314元
        开抢时间: 06月03日 13:24

 INFO  dm_ticket::ticket > 成功生成订单...
 INFO  dm_ticket::ticket > 提交订单失败, 原因:B-00203-200-008::对不起，您选购的商品库存不足，请重新选购, 此次抢购花费时
间:802.305917ms
 INFO  dm_ticket::ticket > 成功生成订单...
 INFO  dm_ticket::ticket > 提交订单失败, 原因:B-00203-200-008::对不起，您选购的商品库存不足，请重新选购, 此次抢购花费时
间:540.572245ms
 INFO  dm_ticket::ticket > 成功生成订单...
 INFO  dm_ticket::ticket > 提交订单失败, 原因:B-00203-200-008::对不起，您选购的商品库存不足，请重新选购, 此次抢购花费时
间:566.273619ms
 INFO  dm_ticket::ticket > 生成订单失败, ["FAIL_SYS_USER_VALIDATE", "RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试"]
 INFO  dm_ticket::ticket > 生成订单失败, ["FAIL_SYS_USER_VALIDATE", "RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试"]
 INFO  dm_ticket::ticket > 生成订单失败, ["FAIL_SYS_USER_VALIDATE", "RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试"]
 INFO  dm_ticket::ticket > 生成订单失败, ["FAIL_SYS_USER_VALIDATE", "RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试"]
 INFO  dm_ticket::ticket > 生成订单失败, ["FAIL_SYS_USER_VALIDATE", "RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试"]
 INFO  dm_ticket::ticket > 生成订单失败, ["FAIL_SYS_USER_VALIDATE", "RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试"]
 INFO  dm_ticket::ticket > 生成订单失败, ["FAIL_SYS_USER_VALIDATE", "RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试"]

**Comment by orz789** [comment]
尝试解决：
退出大麦，重新获取cookie再复制进去，重试。
但又会像这样循环，前几次成功，后面失败。
问，有没有一劳永逸的办法

**Comment by ClassmateLin** [comment]
调整请求频率

**Comment by orz789** [comment]
> 调整请求频率

谢谢，已修改回2次，没有问题

**Comment by orz789** [comment]
@ClassmateLin ![image](https://github.com/ClassmateLin/dm-ticket/assets/135317487/f7eddf11-ee56-45cc-8c68-8b260776e952)
时间相差几秒，修改开抢时间戳也无效。
有无解决办法？是否可以通过调整提前发包时间来实现准时抢？

**Comment by 250king** [comment]
请问一下你是调多少呢？
