### ISSUE TITLE
你好作者，好像dns有点问题？

### ISSUE THREAD

**Issue by aliuzzz** [ClassmateLin/dm-ticket#195]
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: error sending request for url (https://mtop.damai.cn/h5/mtop.damai.wireless.search.broadcast.list/1.0/?): error trying to connect: dns error: failed to lookup address information: Try again

Caused by:
    0: error trying to connect: dns error: failed to lookup address information: Try again
    1: dns error: failed to lookup address information: Try again
    2: failed to lookup address information: Try again', src/bin/ticket.rs:52:66
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by ClassmateLin** [comment]
把环境变量DNS_SERVER注释掉试试

**Comment by mohui1999** [comment]
> 

我注释了，还是不行
