### ISSUE TITLE
关于token-server 服务启动报错

### ISSUE THREAD

**Issue by youaremywind** [ClassmateLin/dm-ticket#197]
使用orbstack 跑的 docker 
重启了docker 和重启了服务都是一样的报错
INFO  alitoken_server > API服务已启动, 正在监听:http://0.0.0.0:8080
 INFO  alitoken_server > 2秒后启动chrome server...
 INFO  actix_server::builder > starting 8 workers
 INFO  actix_server::server  > Tokio runtime found; starting in existing Tokio runtime
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: webDriver command error: webdriver returned error: javascript error: Cannot read properties of undefined (reading 'postFYModule')
  (Session info: headless chrome=112.0.5615.165)', src/main.rs:113:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
想问下这块是做了什么操作为什么会出现这个情况

**Comment by beanbear** [comment]
同样会出现这个问题，0.1.5也一样
