### ISSUE TITLE
Hi 等了很久也运行不了，please help

### ISSUE THREAD

**Issue by William-wAng618** [ClassmateLin/dm-ticket#2]
sudo docker-compose up -d
[+] Running 2/0
 ✔ Container token-server  Running                                                                                                                                                                     0.0s 
 ✔ Container dm-ticket     Running 

sudo docker exec -it dm-ticket dm-ticket

thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: error sending request for url (http://token-server:8080/?key=bx_token): error trying to connect: tcp connect error: Host is unreachable (os error 113)

Caused by:
    0: error trying to connect: tcp connect error: Host is unreachable (os error 113)
    1: tcp connect error: Host is unreachable (os error 113)
    2: Host is unreachable (os error 113)', src/main.rs:28:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by ClassmateLin** [comment]
s

> sudo docker-compose up -d [+] Running 2/0 ✔ Container token-server Running 0.0s ✔ Container dm-ticket Running
> 
> sudo docker exec -it dm-ticket dm-ticket
> 
> thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: error sending request for url (http://token-server:8080/?key=bx_token): error trying to connect: tcp connect error: Host is unreachable (os error 113)
> 
> Caused by: 0: error trying to connect: tcp connect error: Host is unreachable (os error 113) 1: tcp connect error: Host is unreachable (os error 113) 2: Host is unreachable (os error 113)', src/main.rs:28:62 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

搜索 docker Host is unreachable, 应该可以找到解决方案

**Comment by William-wAng618** [comment]
换了台电脑解决了，多谢！
