### ISSUE TITLE
想问一下楼主，如果是要抢即将开票的，需要注意哪些问题呢

### ISSUE THREAD

**Issue by lghcode** [ClassmateLin/dm-ticket#20]
明天上午五月天开票，现在没有机会测试了

**Comment by ClassmateLin** [comment]
提前发包可能有问题，先设置为0。尽量不要抢第一个票档，第一个很难抢。抢第二个票档会容易点。

**Comment by lghcode** [comment]
好的，感谢楼主

**Comment by kaxijun** [comment]
老哥明天上午测试完五月天的后，回来给个体验报告呗

**Comment by lghcode** [comment]
> 老哥明天上午测试完五月天的后，回来给个体验报告呗

行

**Comment by kaxijun** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by joelking666** [comment]
> 明天上午五月天开票，现在没有机会测试了

哈哈哈，你也是杭州的是吧！ 都是竞争对手啊！
