### ISSUE TITLE
docker-compose up报错

### ISSUE THREAD

**Issue by sheeprooo** [ClassmateLin/dm-ticket#201]
运行`docker-compose up`报错
```
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```
![image](https://github.com/ClassmateLin/dm-ticket/assets/74084937/bcd8ba33-03b8-421f-85c0-a2d44d9fbb39)

**Comment by sheeprooo** [comment]
用云服务器直接运行`docker-compose up -d`也报这个错，但是加了sudo之后就成功了，云服务器一直提示爆满，于是改用本机然后报错加了sudo也不行，不是很了解docker，求助求助

**Comment by wht11394** [comment]
你都检查看看docker版本和dc版本吧，再检查别的

**Comment by a2030633** [comment]
docker 都没运行吧

**Comment by kelrose** [comment]
这应该是docker进程没启动，docker ps看输出就知道了、如果输出跟你上边一样就是docker没起来。
