### ISSUE TITLE
捡漏功能panic

### ISSUE THREAD

**Issue by CryBecase** [ClassmateLin/dm-ticket#205]
INFO  dm_ticket::ticket >      未能抢到票, 去捡漏...
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /usr/src/dm-ticket/src/ticket.rs:229:90
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by zsszyx** [comment]
同样
