### ISSUE TITLE
作者有没有试过模拟App点击的方向

### ISSUE THREAD

**Issue by bigsinger** [ClassmateLin/dm-ticket#208]
接口协议的方式很容易被风控，而且长期上看维护成本很高。
模拟点击维护成本低，不容易被风控，长期可用。

一个方向是利用无障碍服务，类似autojs这种，希望可以参考。

**Comment by liyuan1206010227** [comment]
模拟点击没用 到订单提交页面就提交不上。接口方式是成功率最高的

**Comment by benja956** [comment]
我写了个模拟的，程序运行时间一般在360毫秒左右。可能是因为pyautogui库是同步的，感觉时间上没发优化了。

**Comment by bigsinger** [comment]
> 我写了个模拟的，程序运行时间一般在360毫秒左右。可能是因为pyautogui库是同步的，感觉时间上没发优化了。

模拟点击的另外一个优势是可以开多开物理移动设备（手机），然后群控抢，各自用4G/5G网络

**Comment by bigsinger** [comment]
> 我写了个模拟的，程序运行时间一般在360毫秒左右。可能是因为pyautogui库是同步的，感觉时间上没发优化了。

@benja956 可以分享出来看看？
