### ISSUE TITLE
沈阳没抢到

### ISSUE THREAD

**Issue by cczufish** [ClassmateLin/dm-ticket#209]
开抢倒计时:0小时:0分钟:0.023秒   INFO  dm_ticket::ticket > 成功生成订单...
 INFO  dm_ticket::ticket > 未配置实名观演人, 默认选择前4位观演人...
 INFO  dm_ticket::ticket > 提交订单失败, 原因:F-10012-01-16-001::亲，同一时间下单人数过多，建议您稍后再试, 此次抢购花费时间:856.923292ms
 INFO  dm_ticket::ticket > 成功生成订单...
 INFO  dm_ticket::ticket > 未配置实名观演人, 默认选择前4位观演人...
 INFO  dm_ticket::ticket > 提交订单失败, 原因:F-10012-01-16-001::亲，同一时间下单人数过多，建议您稍后再试, 此次抢购花费时间:1.617743599s
 INFO  dm_ticket::ticket > 生成订单失败, ["RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试!"]
 INFO  dm_ticket::ticket >      未能抢到票, 去捡漏...
 INFO  dm_ticket::ticket > 票档:355元（看台）, 有库存, 去购买...
 INFO  dm_ticket::ticket > 生成订单失败, ["RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试!"]
        第1次查询库存, 有余票...无余票... INFO  dm_ticket::ticket > 票档:355元（看台）, 有库存, 去购买...
 INFO  dm_ticket::ticket > 生成订单失败, ["F-10001-10-16-103::对不起，系统繁忙，请稍候再试"]
 INFO  dm_ticket::ticket > 生成订单失败, ["F-10001-10-16-103::对不起，系统繁忙，请稍候再试"]
 INFO  dm_ticket::ticket > 生成订单失败, ["F-10001-10-16-103::对不起，系统繁忙，请稍候再试"]
 INFO  dm_ticket::ticket > 生成订单失败, ["RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试!"]
        第2次查询库存, 有余票...无余票... INFO  dm_ticket::ticket > 票档:355元（看台）, 有库存, 去购买...
 INFO  dm_ticket::ticket > 生成订单失败, ["F-10001-10-16-103::对不起，系统繁忙，请稍候再试"]
 INFO  dm_ticket::ticket > 生成订单失败, ["F-10001-10-16-103::对不起，系统繁忙，请稍候再试"]
 INFO  dm_ticket::ticket > 生成订单失败, ["RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试!"]
        第3次查询库存, 有余票...无余票... INFO  dm_ticket::ticket > 票档:555元（看台）, 有库存, 去购买...
 INFO  dm_ticket::ticket > 生成订单失败, ["RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试!"]
        第4次查询库存, 有余票...无余票... INFO  dm_ticket::ticket > 票档:555元（看台）, 有库存, 去购买...
 INFO  dm_ticket::ticket > 生成订单失败, ["F-10001-10-16-103::对不起，系统繁忙，请稍候再试"]
 INFO  dm_ticket::ticket > 生成订单失败, ["F-10001-10-16-103::对不起，系统繁忙，请稍候再试"]
 INFO  dm_ticket::ticket > 生成订单失败, ["FAIL_SYS_USER_VALIDATE", "RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试"]
        第33次查询库存, 无余票...^Z 票...

有一个成功生成订单，但是app里面没有

**Comment by songjinzhou** [comment]
正常

**Comment by wjzcp** [comment]
一样抢不到

**Comment by xutiruo** [comment]
没抢到+1，是不是要把提前发送订单的时间再调大一点？

**Comment by dc085** [comment]
没抢到+1

**Comment by dc085** [comment]
> 没抢到+1，是不是要把之前发送订单的时间再调大一点？

你现在调的多少

**Comment by otf1810** [comment]
我这提示商品信息过期是怎么回事

**Comment by xutiruo** [comment]
> > 没抢到+1，是不是要把之前发送订单的时间再调大一点？
> 
> 你现在调的多少

我是第一次用，还是设的默认值5
