### ISSUE TITLE
一直thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: error sending request for url (http://172.88.0.2:8080/?key=bx_token): error trying to connect: tcp connect error: Connection refused (os error 111)  Caused by:     0: error trying to connect: tcp connect error: Connection refused (os error 111)     1: tcp connect error: Connection refused (os error 111)     2: Connection refused (os error 111)', src/bin/ticket.rs:52:66 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### ISSUE THREAD

**Issue by HongChenGG** [ClassmateLin/dm-ticket#212]
如何解决，等了很久还是一样
。thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: error sending request for url (http://172.88.0.2:8080/?key=bx_token): error trying to connect: tcp connect error: Connection refused (os error 111)

Caused by:
    0: error trying to connect: tcp connect error: Connection refused (os error 111)
    1: tcp connect error: Connection refused (os error 111)
    2: Connection refused (os error 111)', src/bin/ticket.rs:52:66
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by songjinzhou** [comment]
重启

**Comment by HongChenGG** [comment]
> 重启

重启啥,docker吗，我试过了。

**Comment by songjinzhou** [comment]
重启电脑呢，这是网络问题

**Comment by songjinzhou** [comment]
代理都关了

**Comment by HongChenGG** [comment]
我用的是服务器跑的。也没有用代理
