### ISSUE TITLE
DM抢票不能用了吗？+

### ISSUE THREAD

**Issue by singlem1** [ClassmateLin/dm-ticket#214]
INFO  dm_ticket::client > 请打开大麦APP扫码登录...
 INFO  dm_ticket::client > 用户昵称:微信用户5sOn, 登录成功...
 INFO  dm_ticket::ticket > 微信用户5sOn, 正在检查用户信息...
 INFO  dm_ticket::ticket > 微信用户5sOn, 正在获取演唱会信息...
 INFO  dm_ticket::ticket > 该渠道不支持购买, 请使用APP购票!

该渠道不支持购买怎么回事

**Comment by geekmc** [comment]
你是docker部署的吗？有没有遇到扫码登录没反应的情况

**Comment by singlem1** [comment]
> 您正在部署 docker 吗？有没有遇到扫码登录没有反应的情况

有。

**Comment by geekmc** [comment]
如何解决的呢

**Comment by singlem1** [comment]
> 如何解决的呢

我也不清楚
