### ISSUE TITLE
是否可以配置抢票尝试次数

### ISSUE THREAD

**Issue by ohyex** [ClassmateLin/dm-ticket#22]
哈喽，翻阅了一下代码，发现程序只会进行 2 次抢票行为，代码如下：
https://github.com/ClassmateLin/dm-ticket/blob/a78d4f85a0d0f44e56c8b50c634f3f83212f0321/src/dm.rs#L329-L330
这个地方是否可以配置成 10次 或 100次，还是说如果请求已经发送出去一次之后，重试在多次也是无用的了。不是很了解抢票的防护机制，冒昧提问。

**Comment by ClassmateLin** [comment]
1秒钟票必定抢空。连续请求不sleep, 5次必定触发频繁认证， 后续所有请求都报繁忙。重新登录才能解决。测试sleep最小值是500ms。所以配置10次100次是没有意义的。如果触发了频繁认证。后面加捡漏功能就无法实现

**Comment by ohyex** [comment]
明白了，感谢您的回答。

**Comment by sodargreen** [comment]
> 1秒钟票必定抢空。连续请求不sleep, 5次必定触发频繁认证， 后续所有请求都报繁忙。重新登录才能解决。测试sleep最小值是500ms。所以配置10次100次是没有意义的。如果触发了频繁认证。后面加捡漏功能就无法实现

但是1s内票并不会空，因为我手动抢票的时候订单创建的时间大部分在1分钟内，应该是高并发情况下大部分请求都不会成功，所以我觉得一分钟内一直抢票是有必要的，作者觉得呢？
