### ISSUE TITLE
生成的二维码乱码

### ISSUE THREAD

**Issue by j291356826** [ClassmateLin/dm-ticket#225]
生成的二维码根本识别不了
![Uploading 1689582105995.png…]()

**Comment by j291356826** [comment]
<img width="744" alt="1689582105995" src="https://github.com/ClassmateLin/dm-ticket/assets/42192175/43e1194d-cc4c-41ef-84d1-57fdda9c73bb">

**Comment by Hilbertangers** [comment]
https://github.com/eugeny/tabby 用这个试试

**Comment by j291356826** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by muyi151** [comment]
![image](https://github.com/ClassmateLin/dm-ticket/assets/116507731/40495ac8-8545-44d3-9e71-bf66232768cf)
我的也是，生成的二维码无法识别

**Comment by muyi151** [comment]
请问该怎么解决？

**Comment by j291356826** [comment]
@Hilbertangers 这个可以

**Comment by muyi151** [comment]
> @Hilbertangers这个可以

是的，经过测试，这个生成的二维码可以扫描登录
