### ISSUE TITLE
关于大麦的DoS防御

### ISSUE THREAD

**Issue by HonmaMeikodesu** [ClassmateLin/dm-ticket#26]
大麦这种高并发场景的APP应该会对Dos攻击以及DDos攻击有防范，想问下作者大大有没有试过<b style="font-size: 40px">单账号多设备</b>抢票的用例场景下，会不会被大麦判定为恶意攻击而导致抢票失败？

**Comment by lghcode** [comment]
这个难说

**Comment by ClassmateLin** [comment]
> 大麦这种高并发场景的APP应该会对Dos攻击以及DDos攻击有防范，想问下作者大大有没有试过单账号多设备抢票的用例场景下，会不会被大麦判定为恶意攻击而导致抢票失败？

暂时没有尝试过。你可以尝试一下
