### ISSUE TITLE
一直报错，无法连上token-server

### ISSUE THREAD

**Issue by seanhe** [ClassmateLin/dm-ticket#28]
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: error sending request for url (http://token-server:8082/?key=bx_token): error trying to connect: tcp connect error: Connection refused (os error 111)

Caused by:
    0: error trying to connect: tcp connect error: Connection refused (os error 111)
    1: tcp connect error: Connection refused (os error 111)
    2: Connection refused (os error 111)', src/main.rs:28:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by ClassmateLin** [comment]
![image](https://github.com/ClassmateLin/dm-ticket/assets/53087849/27a0fc1b-7340-4611-978c-128525fc7131)
