### ISSUE TITLE
报错note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### ISSUE THREAD

**Issue by jihuodexiaoyang** [ClassmateLin/dm-ticket#29]
thread 'main' panicked at 'failure to format json str {
  "accounts": [
    {
      "cookie": "cna=hoAcFjbLmXYCAd9oBDBAPFlf; xlly_s=1; _samesite_flag_=true; cookie2=15ba69674f7fea68400af3f0d28eb30b; t=e6d2abacd528a8438fd56c9762a38cb9; _tb_token_=ee8555a7fefae; _hvn_login=18; munb=2215722119188; csg=6499dbea; damai.cn_nickName=%E5%BE%AE%E4%BF%A1%E7%94%A8%E6%88%B7dicn; damai.cn_user=WgXC0VOdiWoLxIdADEBOk2VCEok30vTGu+FtlY9pQXbYkBzGXpETWUrZHmXKOO0gGxb2+Rjuqig=; damai.cn_user_new=WgXC0VOdiWoLxIdADEBOk2VCEok30vTGu%2BFtlY9pQXbYkBzGXpETWUrZHmXKOO0gGxb2%2BRjuqig%3D; h5token=7c7d9275bcbd4641b676e5edd74869ac_1_1; damai_cn_user=WgXC0VOdiWoLxIdADEBOk2VCEok30vTGu%2BFtlY9pQXbYkBzGXpETWUrZHmXKOO0gGxb2%2BRjuqig%3D; loginkey=7c7d9275bcbd4641b676e5edd74869ac_1_1; user_id=231171670; isg=BHl5FvbMORxbh-WInwYmi5pxiOVThm04raXpApuu6KAfIpq07dbGCCkzpAbUmgVw; tfstk=cf_1BtsQoAD1s6zmSdNFPNJ0Ek8VZflWGl9G18wkezy8Rgf1iz0yFfkdmxL2MB1..; l=fBLADf_RN1O78fepBOfZrurza77T7IRPguPzaNbMi9fPO7fHSxvFW1aJXmLMCnGVEsIwo35uBOxXB7LKXyUIQxv9-e98k9lxnddCDa90l",
      "earliest_submit_time": 15,
      "interval": 30,
      "remark": 
      "ticket": {
        "grade": 2,
        "id": "716766808287",
        "num": 1,
        "sessions": 1
      }
    }
  ]
}', src/config.rs:41:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by joelking666** [comment]
我也正好遇到这个错。急急急┭┮﹏┭┮

**Comment by ClassmateLin** [comment]
配置格式错了

**Comment by jihuodexiaoyang** [comment]
配置文件填错了 我的是remark改成自己手机号了，其实应该不变，就是账号1

**Comment by yuansunlight** [comment]
<img width="830" alt="image" src="https://github.com/ClassmateLin/dm-ticket/assets/25894825/5c293e45-1a37-48a8-8dcb-00d67f62c009">
您输入的联系人含特殊字符或长度不符，请修改后重新提交。这个有人遇到吗

**Comment by ClassmateLin** [comment]
> <img alt="image" width="830" src="https://user-images.githubusercontent.com/25894825/241741729-5c293e45-1a37-48a8-8dcb-00d67f62c009.png"> 您输入的联系人含特殊字符或长度不符，请修改后重新提交。这个有人遇到吗

收货地址填一下。

**Comment by jihuodexiaoyang** [comment]
这个没遇到过 是不是你收件人填错了？ 你可以先手动提交订单试一试

**Comment by joelking666** [comment]
> 配置格式错了

thread 'main' panicked at 'failure read file ./config/config.yaml', src/config.rs:34:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

请问这是什么原因

**Comment by ClassmateLin** [comment]
> > 配置格式错了
> 
> thread 'main' panicked at 'failure read file ./config/config.yaml', src/config.rs:34:59 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> 请问这是什么原因

找不到配置文件

**Comment by yuansunlight** [comment]
> > <img alt="image" width="830" src="https://user-images.githubusercontent.com/25894825/241741729-5c293e45-1a37-48a8-8dcb-00d67f62c009.png"> 您输入的联系人含特殊字符或长度不符，请修改后重新提交。这个有人遇到吗
> 
> 收货地址填一下。

可以了，感谢

**Comment by yuansunlight** [comment]
> 这个没遇到过 是不是你收件人填错了？ 你可以先手动提交订单试一试

可以了，感谢，填写了地址就好了

**Comment by joelking666** [comment]
> > > 配置格式错了
> > 
> > 
> > thread 'main' panicked at 'failure read file ./config/config.yaml', src/config.rs:34:59 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > 请问这是什么原因
> 
> 找不到配置文件

但我在dm-ticket 文件目录下运行的docker exec -it dm-ticket dm-ticket
cat ./config/config.yaml 是有的啊

**Comment by jihuodexiaoyang** [comment]
你看看仔细看看配置文件，可能有的地方你小心改错了。

**Comment by jihuodexiaoyang** [comment]
> > > > 配置格式错了
> > > 
> > > 
> > > thread 'main' panicked at 'failure read file ./config/config.yaml', src/config.rs:34:59 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > > 请问这是什么原因
> > 
> > 
> > 找不到配置文件
> 
> 但我在dm-ticket 文件目录下运行的docker exec -it dm-ticket dm-ticket cat ./config/config.yaml 是有的啊

你看看仔细看看配置文件，可能有的地方你小心改错了。

**Comment by joelking666** [comment]
> > > > > 配置格式错了
> > > > 
> > > > 
> > > > thread 'main' panicked at 'failure read file ./config/config.yaml', src/config.rs:34:59 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > > > 请问这是什么原因
> > > 
> > > 
> > > 找不到配置文件
> > 
> > 
> > 但我在dm-ticket 文件目录下运行的docker exec -it dm-ticket dm-ticket cat ./config/config.yaml 是有的啊
> 
> 你看看仔细看看配置文件，可能有的地方你小心改错了。

请问下，你的cookie 是怎么获取的，我直接控制台document.cookie 好像获取不完全？

**Comment by ClassmateLin** [comment]
> > > > > > 配置格式错了
> > > > > 
> > > > > 
> > > > > thread 'main' panicked at 'failure read file ./config/config.yaml', src/config.rs:34:59 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > > > > 请问这是什么原因
> > > > 
> > > > 
> > > > 找不到配置文件
> > > 
> > > 
> > > 但我在dm-ticket 文件目录下运行的docker exec -it dm-ticket dm-ticket cat ./config/config.yaml 是有的啊
> > 
> > 
> > 你看看仔细看看配置文件，可能有的地方你小心改错了。
> 
> 请问下，你的cookie 是怎么获取的，我直接控制台document.cookie 好像获取不完全？

F12找个网络请求，看请求的cookie字段就行了。仓库README.md有图文说明。

**Comment by szx13381** [comment]
remark字段应该填什么啊？

**Comment by jihuodexiaoyang** [comment]
> remark字段应该填什么啊？

不要改 这个参数是固定的

**Comment by ReusChen** [comment]
thread 'main' panicked at 'failure read file ./config/config.yaml', src/config.rs:37:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
我也出现这个，如何解决

**Comment by Invisibleee** [comment]
> 

一样的错误，请问你解决了嘛

**Comment by Invisibleee** [comment]
> > > > 配置格式错了
> > > 
> > > 
> > > thread 'main' panicked at 'failure read file ./config/config.yaml', src/config.rs:34:59 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > > 请问这是什么原因
> > 
> > 
> > 找不到配置文件
> 
> 但我在dm-ticket 文件目录下运行的docker exec -it dm-ticket dm-ticket cat ./config/config.yaml 是有的啊
一样的错误，请问你解决了嘛

**Comment by csx98** [comment]
> > > > > 配置格式错了
> > > > 
> > > > 
> > > > thread 'main' panicked at 'failure read file ./config/config.yaml', src/config.rs:34:59 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > > > 请问这是什么原因
> > > 
> > > 
> > > 找不到配置文件
> > 
> > 
> > 但我在dm-ticket 文件目录下运行的docker exec -it dm-ticket dm-ticket cat ./config/config.yaml 是有的啊
> > 一样的错误，请问你解决了嘛

这错误是配置文件哪里填错了

**Comment by Invisibleee** [comment]
> 



> > > > > > 配置格式错了
> > > > > 
> > > > > 
> > > > > thread 'main' panicked at 'failure read file ./config/config.yaml', src/config.rs:34:59 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > > > > 请问这是什么原因
> > > > 
> > > > 
> > > > 找不到配置文件
> > > 
> > > 
> > > 但我在dm-ticket 文件目录下运行的docker exec -it dm-ticket dm-ticket cat ./config/config.yaml 是有的啊
> > > 一样的错误，请问你解决了嘛
> 
> 这错误是配置文件哪里填错了

同样的配置文件，在windows下正常，在macos上就报这个错555555

**Comment by Dly-orz** [comment]
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: error sending request for url (http://172.88.0.2:8080/?key=bx_token): operation timed out

Caused by:
    operation timed out', src/bin/ticket.rs:52:66
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Dly-orz** [comment]
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: error sending request for url (http://172.88.0.2:8080/?key=bx_token): operation timed out

Caused by:
    operation timed out', src/bin/ticket.rs:52:66
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
这个问题有人遇到过嘛
