### ISSUE TITLE
生成订单失败, ["FAIL_SYS_SESSION_EXPIRED::Session过期"]

### ISSUE THREAD

**Issue by catfish132** [ClassmateLin/dm-ticket#31]
这是为什么呀，session过期

**Comment by ClassmateLin** [comment]
那可能是真的过期了。

**Comment by firstfang** [comment]
> 这是为什么呀，session过期

就是你的cookie过期了

**Comment by iXinjie** [comment]
用Fiddler抓吧，我浏览器抓的Cookie只有几个参数，完整的在应用程序-存储-COOKIE那一栏，但是不好复制

**Comment by ClassmateLin** [comment]
F12就可以了。README.md都有图文说明。

**Comment by LiuyAaa** [comment]
试了很多次，按照readme f12获取了cookie填写到了config中，还是网络开小差了呢？
![微信截图_20230529231310](https://github.com/ClassmateLin/dm-ticket/assets/28710052/f0f0ce6f-da2a-4480-81b2-2ae78d637f7b)
