### ISSUE TITLE
生成订单失败，网络开小差了，再试一次吧~

### ISSUE THREAD

**Issue by firstfang** [ClassmateLin/dm-ticket#32]
![image](https://github.com/ClassmateLin/dm-ticket/assets/49362598/b1c57444-3692-4737-8a73-bcabe9040c47)
大佬，我下午第一次部署好运行成功了，抢票成功，之后更换了cookie一直在提示网络开小差，直接从请求头里复制的cookie应该是完整的。我发现在大麦web端中发起请求每次cookie中isg这个参数都会变，其他参数都是一致的

**Comment by ClassmateLin** [comment]
> ![image](https://user-images.githubusercontent.com/49362598/241756716-b1c57444-3692-4737-8a73-bcabe9040c47.png) 大佬，我下午第一次部署好运行成功了，抢票成功，之后更换了cookie一直在提示网络开小差，直接从请求头里复制的cookie应该是完整的。我发现在大麦web端中发起请求每次cookie中isg这个参数都会变，其他参数都是一致的

尝试把cookie中的isg去除。是否可以正常购买。如果可以我打个hotfix排除isg。

**Comment by firstfang** [comment]
> 

isg不能去除，看样子是我的问题，我再排查一下

**Comment by firstfang** [comment]
问题完结，是场次问题，这个itemid只有一个场次，但是我sessions参数是2
