### ISSUE TITLE
docker镜像拉取失败

### ISSUE THREAD

**Issue by h-q-h9** [ClassmateLin/dm-ticket#35]
![image](https://github.com/ClassmateLin/dm-ticket/assets/75011724/d17e9253-c077-4c04-9988-c8fb07d29fc3)
![image](https://github.com/ClassmateLin/dm-ticket/assets/75011724/80536a24-0582-489c-84c5-14cfbd4ad238)
麻烦看下把

**Comment by ClassmateLin** [comment]
你网络问题

**Comment by 18770171448** [comment]
这显示镜像不存在应该不是网络问题吧，用docker images classmatelin/dm-ticket命令看了下也没有镜像
