### ISSUE TITLE
这是成功了，还是失败了?

### ISSUE THREAD

**Issue by szx13381** [ClassmateLin/dm-ticket#37]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
![image](https://github.com/ClassmateLin/dm-ticket/assets/51104117/28239cb7-67c9-4013-9918-e7610d306b0c)

**Comment by joelking666** [comment]
失败，格式错误捏~(￣▽￣)~*

**Comment by XksA-me** [comment]
1、remark 改成字符串格式，"111111111" 这种，或者直接用非数字，比如 hhh、五月天
2、config.yaml里的空格去掉，再运行看看

**Comment by szx13381** [comment]
![image](https://github.com/ClassmateLin/dm-ticket/assets/51104117/787f83c9-2b66-4893-b01b-391012b4035f)
这个是因为什么呢？

**Comment by szx13381** [comment]
![image](https://github.com/ClassmateLin/dm-ticket/assets/51104117/65606920-0b84-4b9c-8d38-e14578bf0ed6)
还是这个问题了，上个解决了。

**Comment by alifenga** [comment]
INFO  dm_ticket::dm > 生成订单失败, ["RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试!"]
 INFO  dm_ticket::dm > 生成订单失败, ["RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试!"]

一直这个问题咋回事 cookie完整复制的也重新登录了，试试可以直接购票的也不行
