### ISSUE TITLE
调用docker exec -it dm-ticket dm-ticket 超时

### ISSUE THREAD

**Issue by PeterChan10** [ClassmateLin/dm-ticket#38]
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: error sending request for url (http://token-server:8080/?key=bx_token): error trying to connect: tcp connect error: Operation timed out (os error 110)

Caused by:
    0: error trying to connect: tcp connect error: Operation timed out (os error 110)
    1: tcp connect error: Operation timed out (os error 110)
    2: Operation timed out (os error 110)', src/main.rs:28:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by XksA-me** [comment]
看下是不是本地开了代理啥的导致的？

**Comment by kaxijun** [comment]
把 ali-token那个 docker 重新 up 下
