### ISSUE TITLE
Cookies 的时效性有人研究过吗？一般抢票开始前多久开始运行程序？

### ISSUE THREAD

**Issue by XksA-me** [ClassmateLin/dm-ticket#39]
问题：
1、Cookies 的时效性有人研究过吗？
2、一般抢票开始前多久开始运行程序？

**Comment by szx13381** [comment]
同问，提前发包参数的用处

**Comment by joelking666** [comment]
> 问题： 1、Cookies 的时效性有人研究过吗？ 2、一般抢票开始前多久开始运行程序？

我也想知道，但已经快来不及了还有10分钟就要抢了

**Comment by XksA-me** [comment]
还有一分钟 激动，，，

**Comment by XksA-me** [comment]
提前发包的意思是在发包之前还可以改参数吗 比如cookies?
