### ISSUE TITLE
请问启动脚本后没有信息输出是什么原因？

### ISSUE THREAD

**Issue by q871366180** [ClassmateLin/dm-ticket#41]
<img width="506" alt="6d5d4cedc98a69988e8808128e58b45" src="https://github.com/ClassmateLin/dm-ticket/assets/46257137/c338507d-5731-4fae-9555-7c6b413b2d91">

**Comment by ClassmateLin** [comment]
docker-compose down

docker-compose up -d

等2秒再执行docker exec -it dm-ticket dm-ticket

**Comment by q871366180** [comment]
> docker-compose down
> 
> docker-compose up -d
> 
> 等2秒再执行docker exec -it dm-ticket dm-ticket

感谢回复，不过没有解决问题

**Comment by szx13381** [comment]
@ClassmateLin  
![image](https://github.com/ClassmateLin/dm-ticket/assets/51104117/40aef437-9765-4f4d-873f-1804c2580d2c)
大佬，这个是为什么啊？

**Comment by q871366180** [comment]
![image](https://github.com/ClassmateLin/dm-ticket/assets/46257137/ab870b62-e236-4d14-acae-66152ac951f0)
@ClassmateLin 启动日志，不知有没有报错
