### ISSUE TITLE
5月天有人成功的么

### ISSUE THREAD

**Issue by Xchen1995** [ClassmateLin/dm-ticket#45]

**Comment by todd-tao** [comment]
无

**Comment by good-ideal** [comment]
无，没有设置联系人，直接没提交成功

**Comment by AnsonCong** [comment]
提交订单失败, 原因:F-10012-01-16-001::亲，同一时间下单人数过多，建议您稍后再试, 此次抢购花费时间:616.4814ms

**Comment by feifei9606** [comment]
原因同上，+1

**Comment by JianGuoPaPa** [comment]
![image](https://github.com/ClassmateLin/dm-ticket/assets/73806486/96849ffc-616a-4ecf-a26d-26de1be79458)
能帮忙看看这是什么问题不

**Comment by Xchen1995** [comment]
感觉这种调用速度肯定比手动块阿

**Comment by lghcode** [comment]
> 提交订单失败, 原因:F-10012-01-16-001::亲，同一时间下单人数过多，建议您稍后再试, 此次抢购花费时间:616.4814ms
一样

**Comment by lghcode** [comment]
我怀疑是我电脑本机时间慢了几秒啊，我看APP到倒计时完了，我这脚本还有3秒倒计时

**Comment by fourmia** [comment]
> 我怀疑是我电脑本机时间慢了几秒啊，我看APP到倒计时完了，我这脚本还有3秒倒计时

更新下时间吧，另外大麦好像都抢不到
