### ISSUE TITLE
您输入的联系人含特殊字符或长度不符，请修改后重新提交

### ISSUE THREAD

**Issue by xuanxuan000** [ClassmateLin/dm-ticket#47]
提交订单失败, 原因:B-00203-100-037::您输入的联系人含特殊字符或长度不符，请修改后重新提交, 此次抢购花费时间:516.262312ms

**Comment by xiaoping027** [comment]
你先正常下个订单 ，不要付款，收货联系人没写

**Comment by undersix** [comment]
同问

**Comment by xuanxuan000** [comment]
> 

原来是这样  谢谢

**Comment by xuanxuan000** [comment]
> 同问



> 你先正常下个订单 ，不要付款，收货联系人没写

原来是这样 谢谢
