### ISSUE TITLE
不太会安装docker-compose容器

### ISSUE THREAD

**Issue by zgyshuai** [ClassmateLin/dm-ticket#5]
能教学一下嘛，有偿，对于张杰优先购和热门演唱会抢到的几率大不大

**Comment by wangyiidii** [comment]
张杰的都售罄了吧

**Comment by zgyshuai** [comment]
之后还会有张杰优先购，使用您的脚步是不是要在

在 Windows 上安装 Docker Desktop是不是还需要lunux环境
张杰的优先购之后南京会有加场，可以用抓取ck抢优先购嘛，或者加个联系方式，可有偿微信或者qq






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月28日(星期天) 晚上10:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ClassmateLin/dm-ticket] 不太会安装docker-compose容器 (Issue #5)





 
张杰的都售罄了吧

**Comment by ClassmateLin** [comment]
> 之后还会有张杰优先购，使用您的脚步是不是要在 在 Windows 上安装 Docker Desktop是不是还需要lunux环境 张杰的优先购之后南京会有加场，可以用抓取ck抢优先购嘛，或者加个联系方式，可有偿微信或者qq
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年5月28日(星期天) 晚上10:41 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [ClassmateLin/dm-ticket] 不太会安装docker-compose容器 (Issue #5) 张杰的都售罄了吧 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

张杰的票不能再网页端购买，所以无法使用。
