### ISSUE TITLE
您选购的商品信息已过期是我填错了啥吗... 我看其他人可以生成订单，场次票价也一样

### ISSUE THREAD

**Issue by JianGuoPaPa** [ClassmateLin/dm-ticket#50]
![image](https://github.com/ClassmateLin/dm-ticket/assets/73806486/474b17cd-3189-4a84-9878-97c22b89538d)

**Comment by ClassmateLin** [comment]
卖完了

**Comment by JianGuoPaPa** [comment]
🤣太疯狂了，提前发也不行
