### ISSUE TITLE
抢五月天的 提前挂的但是到抢的时候还是显示Session过期是为什么呀

### ISSUE THREAD

**Issue by Hambancluerher** [ClassmateLin/dm-ticket#51]
![608a91ad5e381ca7a1e105a26ee5b91](https://github.com/ClassmateLin/dm-ticket/assets/80746880/b8e9035d-1cfa-40f0-a463-d86ed297ed1f)

**Comment by AnsonCong** [comment]
我是提前10分钟弄的新的cookie

**Comment by lghcode** [comment]
> 我是提前10分钟弄的新的cookie
你抢到了没

**Comment by Hambancluerher** [comment]
> 我是提前10分钟弄的新的cookie

老哥你抢到了吗  我是提前15分钟挂的cookie 是不是太早了

**Comment by ClassmateLin** [comment]
> > 我是提前10分钟弄的新的cookie
> 
> 老哥你抢到了吗 我是提前15分钟挂的cookie 是不是太早了

是不是浏览器点了退出账号？提前半个钟挂都没问题。

**Comment by Hambancluerher** [comment]
> > > 我是提前10分钟弄的新的cookie
> > 
> > 
> > 老哥你抢到了吗 我是提前15分钟挂的cookie 是不是太早了
> 
> 是不是浏览器点了退出账号？提前半个钟挂都没问题。

没有欸 我现在去刷新看的cookie也还是之前那个没变 当时抢的时候我看倒计时卡在0.033秒 然后就报session过期了

**Comment by todd-tao** [comment]
> 

退出账号cookies不会过期

**Comment by AnsonCong** [comment]
> > 我是提前10分钟弄的新的cookie
> > 你抢到了没

没抢到 哈哈哈

**Comment by Hambancluerher** [comment]
> > 
> 
> 退出账号cookies不会过期

我尝试买那些早已经开票的没人买的演唱会的票也报的session过期了 是不是我的cookie有问题？

**Comment by Hambancluerher** [comment]
我知道了 得用chorm浏览器去拿cookie 火狐浏览器拿的cookie不行 QAQ

**Comment by Arecall** [comment]
提前打开是一直在请求，还是会立马退出。

**Comment by ClassmateLin** [comment]
不会请求。等待开抢时间到了才请求

Cherish ***@***.***> 于2023年5月30日周二 15:22写道：
