### ISSUE TITLE
就没一个人成功的嘛！！！

### ISSUE THREAD

**Issue by Xchen1995** [ClassmateLin/dm-ticket#52]

**Comment by myleo1** [comment]
成功的出来冒个泡呀，反正我是没成功T^T

**Comment by todd-tao** [comment]
我看到的都是手动抢到的

**Comment by blingmoon** [comment]
有成功的出来冒个泡吗

**Comment by zhuzhu1001** [comment]
没成功

**Comment by jinfeijie** [comment]
成功了，2张

**Comment by myleo1** [comment]
> 成功了，2张

参数怎么设置的？

**Comment by jinfeijie** [comment]
> > 成功了，2张
> 
> 参数怎么设置的？

就那几个参数，填2张票就好了。我感觉跟网络延迟低有关。我杭州的家庭网络，很稳定

**Comment by myleo1** [comment]
> > > 成功了，2张
> > 
> > 
> > 参数怎么设置的？
> 
> 就那几个参数，填2张票就好了。我感觉跟网络延迟低有关。我杭州的家庭网络，很稳定

我也是杭州的电信家宽，走的有线连接，老哥你设置提前发包了吗？

**Comment by blingmoon** [comment]
> 就好

设置提前发包了吗

**Comment by Xchen1995** [comment]
想看看你的成功日志..

**Comment by Horus-K** [comment]
docker的网络必须和登录大麦的网络是一个吗

**Comment by lghcode** [comment]
> > > 成功了，2张
> > 
> > 
> > 参数怎么设置的？
> 
> 就那几个参数，填2张票就好了。我感觉跟网络延迟低有关。我杭州的家庭网络，很稳定

参数怎么设置，可以看一下吗

**Comment by jinfeijie** [comment]
<img width="1339" alt="image" src="https://github.com/ClassmateLin/dm-ticket/assets/8290380/4f31a34c-9212-440d-a381-458d869a2b59">

**Comment by fzxph** [comment]
> <img alt="image" width="1339" src="https://user-images.githubusercontent.com/8290380/241857199-4f31a34c-9212-440d-a381-458d869a2b59.png">

老哥，windows电脑怎么安装？

**Comment by wwlwwl2000** [comment]
这边大麦脚本可长期提供，有需要的来➕q2091248098，标明github
