### ISSUE TITLE
提交订单失败, 您输入的联系人含特殊字符或长度不符，请修改后重新提交？

### ISSUE THREAD

**Issue by undersix** [ClassmateLin/dm-ticket#53]
提交订单失败, 原因:B-00203-100-037::您输入的联系人含特殊字符或长度不符，请修改后重新提交！！ 我以前用大麦买过东西的 收货地址一直存在

**Comment by chumen77** [comment]
同，已经麻了

**Comment by sailengsi** [comment]
我也发现了，我是新注册的账号，然后把收货地址中新建了一个收件人，姓名和配置文件填写保持一致，成功了。

**Comment by jyC23333** [comment]
@sailengsi 感谢感谢 这是正确解
