### ISSUE TITLE
建议提高尝试次数

### ISSUE THREAD

**Issue by DaisyStar005** [ClassmateLin/dm-ticket#54]
@ClassmateLin  抢票的时候只抢两次程序就退出了，是否可以调高尝试次数到10-20次呢

**Comment by ClassmateLin** [comment]
https://github.com/ClassmateLin/dm-ticket/issues/22

Daisy Star ***@***.***> 于2023年5月30日周二 11:34写道：

**Comment by zxhii** [comment]
> @ClassmateLin 抢票的时候只抢两次程序就退出了，是否可以调高尝试次数到10-20次呢

config里不是可以设置重试次数么
