### ISSUE TITLE
引入IP池是否有用？

### ISSUE THREAD

**Issue by xicYue** [ClassmateLin/dm-ticket#57]

**Comment by ClassmateLin** [comment]
意义不大。大多数代理ip会被拦截，及时可用。速度也不理想。如果买优质的代理贵，还不如动态vps

**Comment by xicYue** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
