### ISSUE TITLE
抢到票了，谢老哥，已打赏

### ISSUE THREAD

**Issue by jinfeijie** [ClassmateLin/dm-ticket#59]
<img width="352" alt="image" src="https://github.com/ClassmateLin/dm-ticket/assets/8290380/e6144011-4d6a-46ec-8453-efb49b940593">

<img width="100" alt="image" src="https://github.com/ClassmateLin/dm-ticket/assets/8290380/384836bd-6172-430e-b9dc-e7187e9b2ff8">

---

程序配置没啥问题，基本上走默认就好。

网络情况
1. 电信家宽300M，独立IP
2. ping值够低
3. 根据ping值调整一下提前发包的时间

**Comment by fourmia** [comment]
> <img alt="image" width="352" src="https://user-images.githubusercontent.com/8290380/241856820-e6144011-4d6a-46ec-8453-efb49b940593.png"> <img alt="image" width="352" src="https://user-images.githubusercontent.com/8290380/241856744-384836bd-6172-430e-b9dc-e7187e9b2ff8.png">

我emo了

**Comment by fzxph** [comment]
老哥，怎么抢的？家用宽带么？

**Comment by jinfeijie** [comment]
> 老哥，怎么抢的？家用宽带么？

是的

**Comment by lghcode** [comment]
我去，配置用的啥配置啊，再问一下，你的号是新号码

**Comment by jinfeijie** [comment]
> 我去，配置用的啥配置啊，再问一下，你的号是新号码

昨晚注册的

**Comment by lghcode** [comment]
> > 我去，配置用的啥配置啊，再问一下，你的号是新号码
> 
> 昨晚注册的

怪不得

**Comment by lghcode** [comment]
能看一下你的订单创建时间和付款时间吗

**Comment by jinfeijie** [comment]
> 能看一下你的订单创建时间和付款时间吗

<img width="239" alt="image" src="https://github.com/ClassmateLin/dm-ticket/assets/8290380/096dc139-0ad6-4874-a525-f71b40426572">

1秒结束，还是慢了

**Comment by jinfeijie** [comment]
> > > 我去，配置用的啥配置啊，再问一下，你的号是新号码
> > 
> > 
> > 昨晚注册的
> 
> 怪不得

昨晚注册的，有什么特殊的吗？

**Comment by lghcode** [comment]
> > > > 我去，配置用的啥配置啊，再问一下，你的号是新号码
> > > 
> > > 
> > > 昨晚注册的
> > 
> > 
> > 怪不得
> 
> 昨晚注册的，有什么特殊的吗？

大麦对新号很友好

**Comment by lghcode** [comment]
> > 能看一下你的订单创建时间和付款时间吗
> 
> <img alt="image" width="239" src="https://user-images.githubusercontent.com/8290380/241860036-096dc139-0ad6-4874-a525-f71b40426572.png">
> 1秒结束，还是慢了

哎呀我去，看样子是以订单创建成功为准啊，你57分付款都行

**Comment by jinfeijie** [comment]
> > > 能看一下你的订单创建时间和付款时间吗
> > 
> > 
> > <img alt="image" width="239" src="https://user-images.githubusercontent.com/8290380/241860036-096dc139-0ad6-4874-a525-f71b40426572.png">
> > 1秒结束，还是慢了
> 
> 哎呀我去，看样子是以订单创建成功为准啊，你57分付款都行

肯定以订单创建为准，支付有15分钟的时间

**Comment by zhuwei12** [comment]
请问您新号实名认证了吗？还是直接录观影人就行？

**Comment by lghcode** [comment]
> > > > 能看一下你的订单创建时间和付款时间吗
> > > 
> > > 
> > > <img alt="image" width="239" src="https://user-images.githubusercontent.com/8290380/241860036-096dc139-0ad6-4874-a525-f71b40426572.png">
> > > 1秒结束，还是慢了
> > 
> > 
> > 哎呀我去，看样子是以订单创建成功为准啊，你57分付款都行
> 
> 肯定以订单创建为准，支付有15分钟的时间

羡慕兄弟

**Comment by jinfeijie** [comment]
> 请问您新号实名认证了吗？还是直接录观影人就行？

观影人

**Comment by Xchen1995** [comment]
希望下一个打赏的是我

**Comment by DistantDream** [comment]
提前发包时间也是跟我一样调成0吗

**Comment by jinfeijie** [comment]
> 提前发包时间也是跟我一样调成0吗

这个无关痛痒吧，不指望第一发就能抢到

**Comment by mamingzxc** [comment]
老哥，有个问题请教下，设置cookie我是整个都复制下来了，结果跑起来提示  ["B-00203-200-100::网络开小差了，再试一次吧~"]
