### ISSUE TITLE
实名制观演场次无法抢票

### ISSUE THREAD

**Issue by DaisyStar005** [ClassmateLin/dm-ticket#6]
测试场次：2023汪峰「UNFOLLOW」巡回演唱会—上海站
itemId: 720545258599 
 INFO  dm_ticket::dm > 提交订单失败, 原因:B-00203-100-037::您输入的联系人含特殊字符或长度不符，请修改后重新提交, 此次抢购花费 时间:1.524336123s

**Comment by DaisyStar005** [comment]
应该需要先判断场次是否需要实名制，然后生成订单的时候需要加一个预选观演人的元素吧？ @ClassmateLin 大佬能否完善一下这个功能

**Comment by fangqiluxatu** [comment]
> 应该需要先判断场次是否需要实名制，然后生成订单的时候需要加一个预选观演人的元素吧？ @ClassmateLin 大佬能否完善一下这个功能

填个收件地址

**Comment by DaisyStar005** [comment]
> > 应该需要先判断场次是否需要实名制，然后生成订单的时候需要加一个预选观演人的元素吧？ @ClassmateLin 大佬能否完善一下这个功能
> 
> 填个收件地址

已解决！感谢！

**Comment by zhouchaogitclub** [comment]
请问是如何解决的
