### ISSUE TITLE
抢票的时间显示的不对

### ISSUE THREAD

**Issue by szx13381** [ClassmateLin/dm-ticket#60]
![image](https://github.com/ClassmateLin/dm-ticket/assets/51104117/d7f08308-a406-4708-be71-0dda704b73a1)

**Comment by ClassmateLin** [comment]
这个时间就是大麦返回的。显示错误。是因为还没开售

**Comment by szx13381** [comment]
@ClassmateLin  那这个需要我设置什么吗？还是需要等开始抢票的那一秒，我在运行docker exec -it dm-ticket dm-ticket呢？

**Comment by ClassmateLin** [comment]
等大麦出现开抢倒计时的时候再跑。离开抢前几分钟跑就行了。

**Comment by szx13381** [comment]
@ClassmateLin  我今天尝试抢正在售卖且有座位的票，为什么也会提示这个错误？

**Comment by Arecall** [comment]
@ClassmateLin 什么时间运行比较好，提前启动这个脚本。

**Comment by wwlwwl2000** [comment]
这边大麦脚本可长期提供，有需要的来➕q2091248098，标明github
