### ISSUE TITLE
RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试!

### ISSUE THREAD

**Issue by flyhai** [ClassmateLin/dm-ticket#63]
测试目前有余票的演出，一直提示RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试!
![Quicker_20230530_151413](https://github.com/ClassmateLin/dm-ticket/assets/11045793/93d477ce-c56c-4d31-a933-5e67bfa189fa)

**Comment by lghcode** [comment]
> 测试目前有余票的演出，一直提示RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试! ![Quicker_20230530_151413](https://user-images.githubusercontent.com/11045793/241877810-93d477ce-c56c-4d31-a933-5e67bfa189fa.png)

看样子你被风控到了

**Comment by AnsonCong** [comment]
把容器杀了重启下 可以解决

**Comment by flyhai** [comment]
已解决，我用云上服务器搭建的dockers，估计ip变了被风控了，本地虚拟机搭建就OK了

**Comment by ClassmateLin** [comment]
> 已解决，我用云上服务器搭建的dockers，估计ip变了被风控了，本地虚拟机搭建就OK了

看REAMME
