### ISSUE TITLE
使用扫描登录后执行抢票报错

### ISSUE THREAD

**Issue by suidu-pro** [ClassmateLin/dm-ticket#67]
thread 'main' panicked at 'failure read file ./config/config.yaml', src/config.rs:37:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by suidu-pro** [comment]
<img width="569" alt="image" src="https://github.com/ClassmateLin/dm-ticket/assets/58975755/9e51b150-3d94-48de-baa0-28009340dc75">

**Comment by ClassmateLin** [comment]
你的配置文件有问题，请检查

**Comment by suidu-pro** [comment]
> 你的配置文件有问题，请检查

这个获取的cooike应该是会自己写入配置文件的吧？

**Comment by Lotus-Blue** [comment]
解决了吗？我也是这个错误

**Comment by suidu-pro** [comment]
> 解决了吗？我也是这个错误
我直接把这个配置文件的后缀改掉了

**Comment by Lotus-Blue** [comment]
![e9881d704c0009123f897a722b586fc](https://github.com/ClassmateLin/dm-ticket/assets/45590660/94963088-73cb-4c13-8498-e79eec25b5d8)

**Comment by Lotus-Blue** [comment]
![image](https://github.com/ClassmateLin/dm-ticket/assets/45590660/4c2a5198-e64a-4aba-8efe-309955a55c54)
