### ISSUE TITLE
 ["FAIL_SYS_SESSION_EXPIRED::Session过期"]是token过期了么

### ISSUE THREAD

**Issue by lyonxh** [ClassmateLin/dm-ticket#68]

**Comment by ReddotCleaner** [comment]
你把扫码之后出现的cookie填入yml了嘛？

**Comment by Huqingnan123** [comment]
扫码之后获取的cookie2=XXX;t=XXX;_tb_token_=XXX;填入yaml之后用汪峰测试会出现生成订单失败, ["FAIL_SYS_HSF_INVOKE_ERROR::抱歉，网络系统异常"]；用控制台复制的cookie又会出现生成订单失败, ["FAIL_SYS_SESSION_EXPIRED::Session过期"]。。。。
