### ISSUE TITLE
INFO  dm_ticket::dm > 生成订单失败, ["FAIL_SYS_HSF_INVOKE_ERROR::抱歉，网络系统异常"]

### ISSUE THREAD

**Issue by ReddotCleaner** [ClassmateLin/dm-ticket#69]
网络异常，在公司摸鱼看到的项目。于是在家里的nas上跑的服务，所以有可能是IP不同触发了风控？

**Comment by 18170967136** [comment]
我也碰到了这个问题，求解决 生成订单失败, ["FAIL_SYS_HSF_INVOKE_ERROR::抱歉，网络系统异常"]
