### ISSUE TITLE
为什么二维码扫码不了

### ISSUE THREAD

**Issue by YIminta** [ClassmateLin/dm-ticket#75]
![image](https://github.com/ClassmateLin/dm-ticket/assets/50685567/99295dc7-f876-49a1-8882-a5924cbcadb5)
这个二维码用大麦APP扫不上，用淘宝可以扫，微信也能扫到，大麦没识别上

**Comment by EkkoG** [comment]
我把生成的二维码贴到了微信里，用微信识别出来了内容，是一个链接 https://m.tb.cn/xxxx，然后把链接用二维码生成工具再生成了一个二维码用大麦扫可以了

**Comment by ClassmateLin** [comment]
APP直接扫有点慢的，白屏等几秒钟就出来了

**Comment by YIminta** [comment]
> APP直接扫有点慢的，白屏等几秒钟就出来了

不是，APP是识别不了这个二维码，我这个是windows环境下的docker，不过我用二楼的方法能扫上了而且也能抢到，感谢老哥，汪峰太惨了都用他去测试 QAQ
![image](https://github.com/ClassmateLin/dm-ticket/assets/50685567/b5524ecc-f957-4a53-a558-4a0d7a2c386e)

**Comment by suidu-pro** [comment]
我昨天还能扫，今天就不行了

**Comment by YIminta** [comment]
> APP直接扫有点慢的，白屏等几秒钟就出来了

![image](https://github.com/ClassmateLin/dm-ticket/assets/50685567/827c3c41-363f-41fd-b386-21a8d66f06cc)
请问我这个cookie配置有问题吗？

**Comment by EkkoG** [comment]
> > APP直接扫有点慢的，白屏等几秒钟就出来了
> 
> ![image](https://user-images.githubusercontent.com/50685567/242156403-827c3c41-363f-41fd-b386-21a8d66f06cc.png) 请问我这个cookie配置有问题吗？

建议删掉吧，cookie 不要随便发

**Comment by Andy-Leong** [comment]
> 

我也是用汪峰的来测试 哈哈哈哈，汪半壁哭晕在厕所

**Comment by YIminta** [comment]
> > > APP直接扫有点慢的，白屏等几秒钟就出来了
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/50685567/242156403-827c3c41-363f-41fd-b386-21a8d66f06cc.png) 请问我这个cookie配置有问题吗？
> 
> 建议删掉吧，cookie 不要随便发

为啥我扫码登录后的cookie贴到配置文件里面不行，要用F12去浏览器拿cookie才可以

**Comment by EkkoG** [comment]
> 

有没有问题我不知道，但是如果没有问题，相当于你把你的号给公开了，别人就可以修改你设置比如密码等等了

**Comment by YIminta** [comment]
> > > 
> > 
> > 
> > 有没有问题我不知道，但是如果没有问题，相当于你把你的号给公开了，别人就可以修改你设置比如密码等等了
> 
> 过期了呀这个cookie

我意思是我现在扫码登录后，把cookie贴过去不行

**Comment by YIminta** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 有没有问题我不知道，但是如果没有问题，相当于你把你的号给公开了，别人就可以修改你设置比如密码等等了
> > > 
> > > 
> > > 过期了呀这个cookie
> > 
> > 
> > 我意思是我现在扫码登录后，把cookie贴过去不行
> 
> 比如如果软件的判断过期逻辑有问题，实际上 cookie 并没有过期呢，你的号是不是就危险了？总之不建议公开发 cookie 就是，只是建议，你要发也没人拦

OK，我打码了，你那个回复得帮忙弄一下qaq

**Comment by jackyyc** [comment]
刚才试了下 要把cookie2= 也要复制进去  然后冒号后面也加了个空格  就可以了

**Comment by YIminta** [comment]
> 刚才试了下 要把cookie2= 也要复制进去 然后冒号后面也加了个空格 就可以了

是拉了最新的docker么，我试了还是不行
