### ISSUE TITLE
大麦是把五月天这场给ban了？

### ISSUE THREAD

**Issue by bobbiezhang** [ClassmateLin/dm-ticket#79]
![image](https://github.com/ClassmateLin/dm-ticket/assets/135093026/efbaf0ba-9def-4caa-9ba0-fcb7ea641b17)
选五月天抢票显示  ["B-00203-200-034::您选购的商品信息已过期，请重新查询"]

选择其他别的演唱会都还能正常抢

**Comment by ClassmateLin** [comment]
早就卖完了。怎么抢

**Comment by nexusal** [comment]
> 早就卖完了。怎么抢
期待捡漏功能~

**Comment by nexusal** [comment]
> 早就卖完了。怎么抢

期待后续的捡漏功能
