### ISSUE TITLE
有没有大佬能讲下提前发包怎么设？

### ISSUE THREAD

**Issue by jyC23333** [ClassmateLin/dm-ticket#80]

**Comment by jyC23333** [comment]
我的意思是怎么根据网络延迟，设置多少是好

**Comment by ClassmateLin** [comment]
https://tool.chinaz.com/dns?type=a&host= DNS查询ip, ping一下ip, 把最快的ip填进去/etc/hosts(可以配合我这个项目https://github.com/ClassmateLin/zzdns)。
`ping mtop.damai.cn`,   比如time=70 ms,  最大值则取70/2。最好再乘以三分之2。具体这么设，你自己慢慢调。确保请求到达服务器的时间大于开抢时间即可。

**Comment by jyC23333** [comment]
@ClassmateLin  感谢，请问下第一个请求在抢票开始前就到达大麦服务器是有什么不良影响吗？

**Comment by DuckDuck88** [comment]
> @ClassmateLin 感谢，请问下第一个请求在抢票开始前就到达大麦服务器是有什么不良影响吗？

到早了没开售抢个锤子...

**Comment by aming98** [comment]
> https://tool.chinaz.com/dns?type=a&host= DNS查询ip, ping一下ip, 把最快的ip填进去/etc/hosts(可以配合我这个项目[https://github.com/ClassmateLin/zzdns)。](https://github.com/ClassmateLin/zzdns)%E3%80%82) `ping mtop.damai.cn`, 比如time=70 ms, 最大值则取70/2。最好再乘以三分之2。具体这么设，你自己慢慢调。确保请求到达服务器的时间大于开抢时间即可。

大佬你好，我在更新docker中的zzdns容器里的/etc/hosts文件时提示文件被占用无法更新，请问是更新这个文件吗，还是更新windows系统里面的hosts文件
