### ISSUE TITLE
仓库地址不对

### ISSUE THREAD

**Issue by SiMaLaoShi** [ClassmateLin/dm-ticket#86]
Pulling token-server (classmatelin/alitoken-server:v0.1.1)...
Trying to pull repository docker.io/classmatelin/alitoken-server ... 
ERROR: manifest for docker.io/classmatelin/alitoken-server:v0.1.1 not found

试过了0.1.1和last都拉不下来，是不是要fq

**Comment by mzzgaopeng** [comment]
<img width="1407" alt="image" src="https://github.com/ClassmateLin/dm-ticket/assets/22125180/1ff2255c-b4e1-450d-90c5-430e3886c3ce">

**Comment by Mystery-cyf** [comment]
我知道有，但是我也拉不下来，登录了也拉不下来

**Comment by Mystery-cyf** [comment]
手动指定registry.docker-cn.com为镜像源就可以拉了

**Comment by LHEway** [comment]
解决了吗
