### ISSUE TITLE
RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试

### ISSUE THREAD

**Issue by HelloEvenZhang** [ClassmateLin/dm-ticket#88]
尝试抢一个可以手动抢的票，一直报错，cookie用的是二维码登陆获得的"cookie2=xxx;_tb_token_=xxx;" ，或者是用网页的cookie"cna=xxxxxx" 都不行，代理开关都一样，是啥问题？
![截屏2023-05-31 16 31 01](https://github.com/ClassmateLin/dm-ticket/assets/59288563/6b921fec-8428-42e8-8147-5e802799a90d)

**Comment by RoseEnd** [comment]
我也是这样

**Comment by linting0406** [comment]
> 尝试抢一个可以手动抢的票，一直报错，cookie用的是二维码登陆获得的"cookie2=xxx;_tb_token_=xxx;" ，或者是用网页的cookie"cna=xxxxxx" 都不行，代理开关都一样，是啥问题？ ![截屏2023-05-31 16 31 01](https://user-images.githubusercontent.com/59288563/242210629-6b921fec-8428-42e8-8147-5e802799a90d.png)

x82y滑块没过就会。作者没开源的

**Comment by HelloEvenZhang** [comment]
> > 尝试抢一个可以手动抢的票，一直报错，cookie用的是二维码登陆获得的"cookie2=xxx;_tb_token_=xxx;" ，或者是用网页的cookie"cna=xxxxxx" 都不行，代理开关都一样，是啥问题？ ![截屏2023-05-31 16 31 01](https://user-images.githubusercontent.com/59288563/242210629-6b921fec-8428-42e8-8147-5e802799a90d.png)
> 
> x82y滑块没过就会。作者没开源的

那请问怎么解决呢？

**Comment by linting0406** [comment]
> > > 尝试抢一个可以手动抢的票，一直报错，cookie用的是二维码登陆获得的"cookie2=xxx;_tb_token_=xxx;" ，或者是用网页的cookie"cna=xxxxxx" 都不行，代理开关都一样，是啥问题？ ![截屏2023-05-31 16 31 01](https://user-images.githubusercontent.com/59288563/242210629-6b921fec-8428-42e8-8147-5e802799a90d.png)
> > 
> > 
> > x82y滑块没过就会。作者没开源的
> 
> 那请问怎么解决呢？

要不自己研究滑块。要不花钱找人写。这块比较值钱。基本没人开源的。算法也在不断变化。
