### ISSUE TITLE
生成订单失败, ["FAIL_SYS_HSF_INVOKE_ERROR::抱歉，网络系统异常"]

### ISSUE THREAD

**Issue by while999** [ClassmateLin/dm-ticket#89]
![image](https://github.com/ClassmateLin/dm-ticket/assets/48550880/3fda217a-4ce0-44e2-82ee-67c3a2dbc7ad)

**Comment by 18170967136** [comment]
是的，我也碰到了这个问题，用的是国外的vps

**Comment by faye0078** [comment]
我也遇到了，why

**Comment by 18170967136** [comment]
整个都要复制下来吗，好像cookie有很长一串

**Comment by faye0078** [comment]
> 整个都要复制下来吗，好像cookie有很长一串

嗯嗯

**Comment by 18170967136** [comment]
好的

**Comment by mamingzxc** [comment]
> > 整个都要复制下来吗，好像cookie有很长一串
> 
> 嗯嗯

复制整个显示 网络开小差了，再试一次吧~

**Comment by zhulingang** [comment]
> 



> > > 整个都要复制下来吗，好像cookie有很长一串
> > 
> > 
> > 嗯嗯
> 
> 复制整个显示 网络开小差了，再试一次吧~

我也是这样，不知道要复制哪个cookie
