### ISSUE TITLE
这是cookie过期的意思吗？

### ISSUE THREAD

**Issue by Andy-Leong** [ClassmateLin/dm-ticket#92]
![WX20230531-170207@2x](https://github.com/ClassmateLin/dm-ticket/assets/15701788/9816cd32-3b11-46cb-9f98-07f876b4be70)

**Comment by YIminta** [comment]
cookie过期或者cookie复制少了都有可能

**Comment by Andy-Leong** [comment]
> cookie过期或者cookie复制少了都有可能

嗯嗯，是过期了

**Comment by YIminta** [comment]
> > cookie过期或者cookie复制少了都有可能
> 
> 嗯嗯，是过期了

你是拿控制台的cookie，还是拿扫码登录后的cookie

**Comment by faye0078** [comment]
cookie是全部都要复制吗？还是只要cookie2呀？
![WechatIMG98](https://github.com/ClassmateLin/dm-ticket/assets/63387941/1c8c1aa7-5a16-48b1-ad69-1355e3a1430f)

**Comment by DuckDuck88** [comment]
> cookie是全部都要复制吗？还是只要cookie2呀？ ![WechatIMG98](https://user-images.githubusercontent.com/63387941/242229301-1c8c1aa7-5a16-48b1-ad69-1355e3a1430f.png)

全部复制...
