### ISSUE TITLE
您输入的联系人含特殊字符或长度不符，请修改后重新提交

### ISSUE THREAD

**Issue by xiehaitang** [ClassmateLin/dm-ticket#93]
INFO  dm_ticket::dm > 成功生成订单...
 INFO  dm_ticket::dm > 提交订单失败, 原因:B-00203-100-037::您输入的联系人含特殊字符或长度不符，请修改后重新提交, 此次抢购花费时间:782.740197ms
 INFO  dm_ticket::dm > 成功生成订单...
 INFO  dm_ticket::dm > 提交订单失败, 原因:B-00203-100-037::您输入的联系人含特殊字符或长度不符，请修改后重新提交, 此次抢购花费时间:675.279013ms

**Comment by xiehaitang** [comment]
购票需要填写联系人，脚本没有联系人这个填写的地方

**Comment by karhank** [comment]
> 购票需要填写联系人，脚本没有联系人这个填写的地方

去大麦网亲自下一次单把常用联系人和快递地址都填了然后取消出来
