### ISSUE TITLE
原理。

### ISSUE THREAD

**Issue by csh0101** [ClassmateLin/dm-ticket#95]
这个项目的原理是不是抓了h5 dm的包，然后疯狂模拟发request呀？ 扫了一眼代码 没看到爬虫相关的代码（还以为是那种全自动的扫票工具）

请教请教

**Comment by ClassmateLin** [comment]
> 这个项目的原理是不是抓了h5 dm的包，然后疯狂模拟发request呀？ 扫了一眼代码 没看到爬虫相关的代码（还以为是那种全自动的扫票工具）
> 
> 请教请教

看源码

**Comment by csh0101** [comment]
> > 这个项目的原理是不是抓了h5 dm的包，然后疯狂模拟发request呀？ 扫了一眼代码 没看到爬虫相关的代码（还以为是那种全自动的扫票工具）
> > 请教请教
> 
> 看源码

看了才来问的 验证一下自己的理解。
