### ISSUE TITLE
无法拉取服务

### ISSUE THREAD

**Issue by LHEway** [ClassmateLin/dm-ticket#99]
Pulling token-server (classmatelin/alitoken-server:latest)...
Trying to pull repository docker.io/classmatelin/alitoken-server ...
ERROR: repository docker.io/classmatelin/alitoken-server not found: does not exist or no pull access

**Comment by banben** [comment]
Error response from daemon: pull access denied for classmatelin/alitoken-server, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
ffq@ffq-desktop:/data3/dm/dm-ticket$ docker pull classmatelin/alitoken-server:v0.1.1^C
我也不想

**Comment by shuoshadow** [comment]
镜像被删了吗？alitoken-server

**Comment by 18170967136** [comment]
无法拉取服务了！

**Comment by 18170967136** [comment]
应该是在更新扫码的bug吧，可是，啥时候更新完啊┭┮﹏┭┮

**Comment by hsx001** [comment]
+1  Pulling token-server (classmatelin/alitoken-server:latest)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

**Comment by candlewill** [comment]
+1 alitoken-server已经删除，不存在了

**Comment by shuoshadow** [comment]
> 作者好像被气到了，哎

为啥，被什么事气到了？

**Comment by lghcode** [comment]
> > 作者好像被气到了，哎
> 
> 为啥，被什么事气到了？
78楼搁那阴阳怪气
